---
title: 'Song Recommender System '
description: |
  Recommender System on Implicit Feedback Dataset (Number artist playcount)
title-block-banner: true
date: '2023-17-07'
categories:
  - projects
  - recommender system 
  
code-fold: show
draft: false
jupyter: minids
---

![Website](song_unsplash.jpg)
<center>Photo by <a href="https://unsplash.com/@kpebedko_o?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Oleg Sergeichik</a> on <a href="https://unsplash.com/photos/Ebhh_t6tjo0?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>
  </center>

In [1]:
import pandas as pd 
import numpy as np 
import os

In [2]:

artist_user_path = 'interim_user_artists.csv'

In [3]:
artist_user_df = pd.read_csv(artist_user_path)

In [4]:
artist_user_df

       userID  artistID  weight
0           2        51   13883
1           2        52   11690
2           2        53   11351
3           2        54   10300
4           2        55    8983
...       ...       ...     ...
92829    2100     18726     337
92830    2100     18727     297
92831    2100     18728     281
92832    2100     18729     280
92833    2100     18730     263

[92834 rows x 3 columns]

In [15]:
#map user id --> ordered id 
user_id_to_ordered_id = {}
ordered_id_to_user_id = {}
for idx,user_id in enumerate(artist_user_df['userID'].unique()) : 
    user_id_to_ordered_id[user_id] = idx+1
    ordered_id_to_user_id[idx+1] = user_id

In [16]:
user_id_to_ordered_id

{2: 1,
 3: 2,
 4: 3,
 5: 4,
 6: 5,
 7: 6,
 8: 7,
 9: 8,
 10: 9,
 11: 10,
 12: 11,
 13: 12,
 14: 13,
 15: 14,
 16: 15,
 17: 16,
 18: 17,
 20: 18,
 21: 19,
 22: 20,
 23: 21,
 24: 22,
 25: 23,
 26: 24,
 27: 25,
 28: 26,
 29: 27,
 30: 28,
 31: 29,
 32: 30,
 33: 31,
 34: 32,
 35: 33,
 36: 34,
 37: 35,
 38: 36,
 39: 37,
 40: 38,
 41: 39,
 42: 40,
 43: 41,
 44: 42,
 45: 43,
 46: 44,
 47: 45,
 48: 46,
 49: 47,
 50: 48,
 51: 49,
 52: 50,
 53: 51,
 54: 52,
 55: 53,
 56: 54,
 57: 55,
 58: 56,
 59: 57,
 60: 58,
 61: 59,
 62: 60,
 63: 61,
 64: 62,
 65: 63,
 66: 64,
 68: 65,
 69: 66,
 70: 67,
 71: 68,
 72: 69,
 73: 70,
 74: 71,
 75: 72,
 76: 73,
 77: 74,
 78: 75,
 79: 76,
 80: 77,
 81: 78,
 82: 79,
 83: 80,
 84: 81,
 85: 82,
 86: 83,
 87: 84,
 88: 85,
 89: 86,
 90: 87,
 91: 88,
 92: 89,
 94: 90,
 95: 91,
 96: 92,
 97: 93,
 98: 94,
 99: 95,
 100: 96,
 101: 97,
 102: 98,
 103: 99,
 104: 100,
 105: 101,
 106: 102,
 107: 103,
 108: 104,
 109: 105,
 110: 106,
 111: 107,
 112: 108,
 113: 109,
 114: 110,
 115: 111,
 116: 112,
 117: 113,
 118: 114,
 119: 115,
 120: 116,
 121: 117,
 122: 118,
 123: 119,
 124: 120,
 125: 121,
 126: 122,
 127: 123,
 128: 124,
 129: 125,
 130: 126,
 131: 127,
 132: 128,
 133: 129,
 134: 130,
 135: 131,
 136: 132,
 137: 133,
 139: 134,
 140: 135,
 141: 136,
 142: 137,
 143: 138,
 144: 139,
 145: 140,
 146: 141,
 147: 142,
 148: 143,
 149: 144,
 150: 145,
 151: 146,
 152: 147,
 153: 148,
 154: 149,
 155: 150,
 156: 151,
 157: 152,
 158: 153,
 159: 154,
 161: 155,
 162: 156,
 163: 157,
 164: 158,
 166: 159,
 168: 160,
 170: 161,
 171: 162,
 172: 163,
 173: 164,
 174: 165,
 175: 166,
 176: 167,
 177: 168,
 178: 169,
 179: 170,
 180: 171,
 181: 172,
 182: 173,
 183: 174,
 184: 175,
 185: 176,
 186: 177,
 187: 178,
 188: 179,
 189: 180,
 190: 181,
 191: 182,
 192: 183,
 193: 184,
 194: 185,
 195: 186,
 196: 187,
 198: 188,
 200: 189,
 201: 190,
 202: 191,
 203: 192,
 204: 193,
 205: 194,
 206: 195,
 207: 196,
 208: 197,
 209: 198,
 210: 199,
 211: 200,
 212: 201,
 213: 202,
 214: 203,
 215: 204,
 216: 205,
 217: 206,
 218: 207,
 219: 208,
 220: 209,
 223: 210,
 224: 211,
 225: 212,
 226: 213,
 227: 214,
 228: 215,
 229: 216,
 230: 217,
 231: 218,
 232: 219,
 233: 220,
 234: 221,
 235: 222,
 236: 223,
 237: 224,
 238: 225,
 240: 226,
 241: 227,
 242: 228,
 243: 229,
 244: 230,
 247: 231,
 248: 232,
 249: 233,
 250: 234,
 251: 235,
 252: 236,
 253: 237,
 254: 238,
 255: 239,
 256: 240,
 257: 241,
 258: 242,
 259: 243,
 260: 244,
 261: 245,
 262: 246,
 263: 247,
 264: 248,
 265: 249,
 266: 250,
 267: 251,
 268: 252,
 269: 253,
 270: 254,
 271: 255,
 273: 256,
 274: 257,
 275: 258,
 277: 259,
 278: 260,
 279: 261,
 280: 262,
 281: 263,
 282: 264,
 283: 265,
 284: 266,
 285: 267,
 286: 268,
 288: 269,
 289: 270,
 290: 271,
 291: 272,
 292: 273,
 293: 274,
 294: 275,
 295: 276,
 296: 277,
 297: 278,
 298: 279,
 299: 280,
 300: 281,
 301: 282,
 302: 283,
 303: 284,
 304: 285,
 305: 286,
 306: 287,
 307: 288,
 308: 289,
 310: 290,
 311: 291,
 312: 292,
 313: 293,
 314: 294,
 315: 295,
 316: 296,
 317: 297,
 318: 298,
 319: 299,
 320: 300,
 321: 301,
 322: 302,
 324: 303,
 325: 304,
 326: 305,
 327: 306,
 328: 307,
 329: 308,
 330: 309,
 331: 310,
 332: 311,
 333: 312,
 334: 313,
 335: 314,
 336: 315,
 337: 316,
 338: 317,
 339: 318,
 340: 319,
 341: 320,
 342: 321,
 343: 322,
 344: 323,
 345: 324,
 346: 325,
 347: 326,
 348: 327,
 349: 328,
 350: 329,
 351: 330,
 352: 331,
 353: 332,
 354: 333,
 355: 334,
 356: 335,
 357: 336,
 358: 337,
 359: 338,
 360: 339,
 361: 340,
 362: 341,
 363: 342,
 364: 343,
 365: 344,
 366: 345,
 367: 346,
 368: 347,
 369: 348,
 370: 349,
 371: 350,
 372: 351,
 374: 352,
 375: 353,
 376: 354,
 377: 355,
 378: 356,
 380: 357,
 382: 358,
 383: 359,
 385: 360,
 386: 361,
 387: 362,
 388: 363,
 390: 364,
 391: 365,
 392: 366,
 393: 367,
 394: 368,
 395: 369,
 396: 370,
 397: 371,
 398: 372,
 399: 373,
 400: 374,
 401: 375,
 402: 376,
 403: 377,
 404: 378,
 405: 379,
 406: 380,
 407: 381,
 408: 382,
 409: 383,
 410: 384,
 411: 385,
 412: 386,
 413: 387,
 414: 388,
 415: 389,
 416: 390,
 417: 391,
 418: 392,
 419: 393,
 420: 394,
 421: 395,
 423: 396,
 424: 397,
 425: 398,
 426: 399,
 427: 400,
 428: 401,
 430: 402,
 431: 403,
 432: 404,
 433: 405,
 434: 406,
 435: 407,
 436: 408,
 437: 409,
 438: 410,
 439: 411,
 440: 412,
 441: 413,
 442: 414,
 443: 415,
 444: 416,
 446: 417,
 447: 418,
 449: 419,
 450: 420,
 451: 421,
 452: 422,
 453: 423,
 454: 424,
 455: 425,
 456: 426,
 457: 427,
 458: 428,
 459: 429,
 460: 430,
 461: 431,
 462: 432,
 463: 433,
 464: 434,
 465: 435,
 466: 436,
 467: 437,
 468: 438,
 469: 439,
 470: 440,
 471: 441,
 472: 442,
 473: 443,
 474: 444,
 475: 445,
 476: 446,
 477: 447,
 478: 448,
 479: 449,
 480: 450,
 481: 451,
 482: 452,
 484: 453,
 485: 454,
 486: 455,
 487: 456,
 488: 457,
 489: 458,
 490: 459,
 491: 460,
 492: 461,
 493: 462,
 494: 463,
 495: 464,
 496: 465,
 497: 466,
 498: 467,
 499: 468,
 500: 469,
 501: 470,
 502: 471,
 503: 472,
 504: 473,
 506: 474,
 507: 475,
 508: 476,
 509: 477,
 510: 478,
 511: 479,
 512: 480,
 513: 481,
 514: 482,
 515: 483,
 516: 484,
 517: 485,
 518: 486,
 519: 487,
 520: 488,
 521: 489,
 523: 490,
 525: 491,
 526: 492,
 527: 493,
 529: 494,
 530: 495,
 531: 496,
 532: 497,
 533: 498,
 534: 499,
 535: 500,
 536: 501,
 537: 502,
 538: 503,
 539: 504,
 540: 505,
 541: 506,
 542: 507,
 543: 508,
 544: 509,
 545: 510,
 546: 511,
 547: 512,
 548: 513,
 549: 514,
 550: 515,
 551: 516,
 552: 517,
 553: 518,
 555: 519,
 556: 520,
 557: 521,
 558: 522,
 559: 523,
 560: 524,
 561: 525,
 562: 526,
 563: 527,
 565: 528,
 566: 529,
 567: 530,
 568: 531,
 569: 532,
 570: 533,
 571: 534,
 572: 535,
 573: 536,
 574: 537,
 575: 538,
 576: 539,
 577: 540,
 578: 541,
 579: 542,
 580: 543,
 581: 544,
 582: 545,
 583: 546,
 584: 547,
 585: 548,
 586: 549,
 587: 550,
 589: 551,
 590: 552,
 592: 553,
 593: 554,
 594: 555,
 595: 556,
 596: 557,
 598: 558,
 601: 559,
 602: 560,
 603: 561,
 604: 562,
 605: 563,
 606: 564,
 607: 565,
 608: 566,
 609: 567,
 611: 568,
 612: 569,
 613: 570,
 614: 571,
 615: 572,
 616: 573,
 617: 574,
 618: 575,
 619: 576,
 620: 577,
 621: 578,
 622: 579,
 623: 580,
 624: 581,
 625: 582,
 627: 583,
 628: 584,
 629: 585,
 631: 586,
 632: 587,
 633: 588,
 634: 589,
 635: 590,
 636: 591,
 637: 592,
 638: 593,
 639: 594,
 640: 595,
 641: 596,
 642: 597,
 643: 598,
 644: 599,
 645: 600,
 646: 601,
 647: 602,
 649: 603,
 650: 604,
 651: 605,
 652: 606,
 654: 607,
 655: 608,
 656: 609,
 657: 610,
 658: 611,
 659: 612,
 660: 613,
 661: 614,
 662: 615,
 663: 616,
 664: 617,
 665: 618,
 666: 619,
 667: 620,
 668: 621,
 669: 622,
 670: 623,
 671: 624,
 672: 625,
 673: 626,
 674: 627,
 675: 628,
 676: 629,
 677: 630,
 678: 631,
 679: 632,
 680: 633,
 681: 634,
 682: 635,
 683: 636,
 684: 637,
 685: 638,
 686: 639,
 687: 640,
 688: 641,
 689: 642,
 690: 643,
 691: 644,
 692: 645,
 693: 646,
 694: 647,
 695: 648,
 696: 649,
 697: 650,
 698: 651,
 699: 652,
 700: 653,
 701: 654,
 702: 655,
 703: 656,
 704: 657,
 705: 658,
 706: 659,
 707: 660,
 708: 661,
 709: 662,
 710: 663,
 711: 664,
 712: 665,
 713: 666,
 714: 667,
 715: 668,
 716: 669,
 717: 670,
 718: 671,
 719: 672,
 720: 673,
 721: 674,
 722: 675,
 723: 676,
 725: 677,
 726: 678,
 727: 679,
 728: 680,
 729: 681,
 730: 682,
 731: 683,
 732: 684,
 733: 685,
 734: 686,
 735: 687,
 736: 688,
 737: 689,
 738: 690,
 739: 691,
 741: 692,
 742: 693,
 743: 694,
 744: 695,
 745: 696,
 746: 697,
 747: 698,
 749: 699,
 750: 700,
 751: 701,
 752: 702,
 753: 703,
 754: 704,
 756: 705,
 757: 706,
 758: 707,
 759: 708,
 760: 709,
 761: 710,
 762: 711,
 763: 712,
 764: 713,
 765: 714,
 767: 715,
 768: 716,
 769: 717,
 770: 718,
 771: 719,
 772: 720,
 773: 721,
 776: 722,
 777: 723,
 778: 724,
 779: 725,
 780: 726,
 781: 727,
 782: 728,
 784: 729,
 785: 730,
 786: 731,
 787: 732,
 788: 733,
 789: 734,
 790: 735,
 791: 736,
 792: 737,
 793: 738,
 794: 739,
 795: 740,
 797: 741,
 798: 742,
 799: 743,
 800: 744,
 801: 745,
 802: 746,
 804: 747,
 805: 748,
 806: 749,
 807: 750,
 808: 751,
 809: 752,
 810: 753,
 812: 754,
 813: 755,
 814: 756,
 815: 757,
 816: 758,
 817: 759,
 818: 760,
 819: 761,
 820: 762,
 821: 763,
 822: 764,
 823: 765,
 824: 766,
 825: 767,
 826: 768,
 827: 769,
 828: 770,
 829: 771,
 830: 772,
 831: 773,
 832: 774,
 834: 775,
 835: 776,
 836: 777,
 837: 778,
 838: 779,
 839: 780,
 840: 781,
 841: 782,
 842: 783,
 843: 784,
 844: 785,
 845: 786,
 846: 787,
 847: 788,
 848: 789,
 849: 790,
 850: 791,
 851: 792,
 852: 793,
 853: 794,
 854: 795,
 855: 796,
 856: 797,
 858: 798,
 859: 799,
 860: 800,
 861: 801,
 862: 802,
 863: 803,
 864: 804,
 865: 805,
 868: 806,
 869: 807,
 870: 808,
 871: 809,
 873: 810,
 874: 811,
 875: 812,
 876: 813,
 877: 814,
 878: 815,
 881: 816,
 882: 817,
 884: 818,
 885: 819,
 886: 820,
 887: 821,
 888: 822,
 889: 823,
 890: 824,
 891: 825,
 893: 826,
 895: 827,
 896: 828,
 897: 829,
 898: 830,
 899: 831,
 900: 832,
 903: 833,
 904: 834,
 905: 835,
 906: 836,
 907: 837,
 908: 838,
 909: 839,
 910: 840,
 911: 841,
 912: 842,
 913: 843,
 914: 844,
 915: 845,
 916: 846,
 917: 847,
 919: 848,
 920: 849,
 921: 850,
 922: 851,
 924: 852,
 925: 853,
 926: 854,
 927: 855,
 928: 856,
 929: 857,
 930: 858,
 931: 859,
 932: 860,
 933: 861,
 934: 862,
 935: 863,
 936: 864,
 938: 865,
 939: 866,
 940: 867,
 941: 868,
 942: 869,
 943: 870,
 946: 871,
 948: 872,
 949: 873,
 950: 874,
 951: 875,
 952: 876,
 953: 877,
 954: 878,
 955: 879,
 957: 880,
 958: 881,
 959: 882,
 960: 883,
 961: 884,
 962: 885,
 963: 886,
 964: 887,
 965: 888,
 966: 889,
 967: 890,
 968: 891,
 969: 892,
 971: 893,
 972: 894,
 975: 895,
 976: 896,
 977: 897,
 978: 898,
 979: 899,
 980: 900,
 981: 901,
 982: 902,
 984: 903,
 985: 904,
 986: 905,
 987: 906,
 989: 907,
 990: 908,
 991: 909,
 993: 910,
 994: 911,
 995: 912,
 996: 913,
 997: 914,
 998: 915,
 999: 916,
 1001: 917,
 1002: 918,
 1003: 919,
 1004: 920,
 1005: 921,
 1006: 922,
 1007: 923,
 1008: 924,
 1009: 925,
 1010: 926,
 1011: 927,
 1012: 928,
 1013: 929,
 1014: 930,
 1015: 931,
 1016: 932,
 1017: 933,
 1018: 934,
 1019: 935,
 1020: 936,
 1021: 937,
 1022: 938,
 1023: 939,
 1024: 940,
 1025: 941,
 1026: 942,
 1027: 943,
 1028: 944,
 1029: 945,
 1030: 946,
 1032: 947,
 1033: 948,
 1034: 949,
 1035: 950,
 1036: 951,
 1037: 952,
 1038: 953,
 1039: 954,
 1040: 955,
 1041: 956,
 1042: 957,
 1044: 958,
 1046: 959,
 1047: 960,
 1049: 961,
 1050: 962,
 1051: 963,
 1052: 964,
 1053: 965,
 1054: 966,
 1055: 967,
 1056: 968,
 1057: 969,
 1058: 970,
 1060: 971,
 1061: 972,
 1062: 973,
 1063: 974,
 1064: 975,
 1065: 976,
 1067: 977,
 1068: 978,
 1069: 979,
 1070: 980,
 1071: 981,
 1072: 982,
 1073: 983,
 1074: 984,
 1075: 985,
 1076: 986,
 1078: 987,
 1079: 988,
 1080: 989,
 1081: 990,
 1082: 991,
 1083: 992,
 1084: 993,
 1085: 994,
 1086: 995,
 1087: 996,
 1088: 997,
 1089: 998,
 1090: 999,
 1091: 1000,
 ...}

In [17]:
ordered_id_to_user_id

{1: 2,
 2: 3,
 3: 4,
 4: 5,
 5: 6,
 6: 7,
 7: 8,
 8: 9,
 9: 10,
 10: 11,
 11: 12,
 12: 13,
 13: 14,
 14: 15,
 15: 16,
 16: 17,
 17: 18,
 18: 20,
 19: 21,
 20: 22,
 21: 23,
 22: 24,
 23: 25,
 24: 26,
 25: 27,
 26: 28,
 27: 29,
 28: 30,
 29: 31,
 30: 32,
 31: 33,
 32: 34,
 33: 35,
 34: 36,
 35: 37,
 36: 38,
 37: 39,
 38: 40,
 39: 41,
 40: 42,
 41: 43,
 42: 44,
 43: 45,
 44: 46,
 45: 47,
 46: 48,
 47: 49,
 48: 50,
 49: 51,
 50: 52,
 51: 53,
 52: 54,
 53: 55,
 54: 56,
 55: 57,
 56: 58,
 57: 59,
 58: 60,
 59: 61,
 60: 62,
 61: 63,
 62: 64,
 63: 65,
 64: 66,
 65: 68,
 66: 69,
 67: 70,
 68: 71,
 69: 72,
 70: 73,
 71: 74,
 72: 75,
 73: 76,
 74: 77,
 75: 78,
 76: 79,
 77: 80,
 78: 81,
 79: 82,
 80: 83,
 81: 84,
 82: 85,
 83: 86,
 84: 87,
 85: 88,
 86: 89,
 87: 90,
 88: 91,
 89: 92,
 90: 94,
 91: 95,
 92: 96,
 93: 97,
 94: 98,
 95: 99,
 96: 100,
 97: 101,
 98: 102,
 99: 103,
 100: 104,
 101: 105,
 102: 106,
 103: 107,
 104: 108,
 105: 109,
 106: 110,
 107: 111,
 108: 112,
 109: 113,
 110: 114,
 111: 115,
 112: 116,
 113: 117,
 114: 118,
 115: 119,
 116: 120,
 117: 121,
 118: 122,
 119: 123,
 120: 124,
 121: 125,
 122: 126,
 123: 127,
 124: 128,
 125: 129,
 126: 130,
 127: 131,
 128: 132,
 129: 133,
 130: 134,
 131: 135,
 132: 136,
 133: 137,
 134: 139,
 135: 140,
 136: 141,
 137: 142,
 138: 143,
 139: 144,
 140: 145,
 141: 146,
 142: 147,
 143: 148,
 144: 149,
 145: 150,
 146: 151,
 147: 152,
 148: 153,
 149: 154,
 150: 155,
 151: 156,
 152: 157,
 153: 158,
 154: 159,
 155: 161,
 156: 162,
 157: 163,
 158: 164,
 159: 166,
 160: 168,
 161: 170,
 162: 171,
 163: 172,
 164: 173,
 165: 174,
 166: 175,
 167: 176,
 168: 177,
 169: 178,
 170: 179,
 171: 180,
 172: 181,
 173: 182,
 174: 183,
 175: 184,
 176: 185,
 177: 186,
 178: 187,
 179: 188,
 180: 189,
 181: 190,
 182: 191,
 183: 192,
 184: 193,
 185: 194,
 186: 195,
 187: 196,
 188: 198,
 189: 200,
 190: 201,
 191: 202,
 192: 203,
 193: 204,
 194: 205,
 195: 206,
 196: 207,
 197: 208,
 198: 209,
 199: 210,
 200: 211,
 201: 212,
 202: 213,
 203: 214,
 204: 215,
 205: 216,
 206: 217,
 207: 218,
 208: 219,
 209: 220,
 210: 223,
 211: 224,
 212: 225,
 213: 226,
 214: 227,
 215: 228,
 216: 229,
 217: 230,
 218: 231,
 219: 232,
 220: 233,
 221: 234,
 222: 235,
 223: 236,
 224: 237,
 225: 238,
 226: 240,
 227: 241,
 228: 242,
 229: 243,
 230: 244,
 231: 247,
 232: 248,
 233: 249,
 234: 250,
 235: 251,
 236: 252,
 237: 253,
 238: 254,
 239: 255,
 240: 256,
 241: 257,
 242: 258,
 243: 259,
 244: 260,
 245: 261,
 246: 262,
 247: 263,
 248: 264,
 249: 265,
 250: 266,
 251: 267,
 252: 268,
 253: 269,
 254: 270,
 255: 271,
 256: 273,
 257: 274,
 258: 275,
 259: 277,
 260: 278,
 261: 279,
 262: 280,
 263: 281,
 264: 282,
 265: 283,
 266: 284,
 267: 285,
 268: 286,
 269: 288,
 270: 289,
 271: 290,
 272: 291,
 273: 292,
 274: 293,
 275: 294,
 276: 295,
 277: 296,
 278: 297,
 279: 298,
 280: 299,
 281: 300,
 282: 301,
 283: 302,
 284: 303,
 285: 304,
 286: 305,
 287: 306,
 288: 307,
 289: 308,
 290: 310,
 291: 311,
 292: 312,
 293: 313,
 294: 314,
 295: 315,
 296: 316,
 297: 317,
 298: 318,
 299: 319,
 300: 320,
 301: 321,
 302: 322,
 303: 324,
 304: 325,
 305: 326,
 306: 327,
 307: 328,
 308: 329,
 309: 330,
 310: 331,
 311: 332,
 312: 333,
 313: 334,
 314: 335,
 315: 336,
 316: 337,
 317: 338,
 318: 339,
 319: 340,
 320: 341,
 321: 342,
 322: 343,
 323: 344,
 324: 345,
 325: 346,
 326: 347,
 327: 348,
 328: 349,
 329: 350,
 330: 351,
 331: 352,
 332: 353,
 333: 354,
 334: 355,
 335: 356,
 336: 357,
 337: 358,
 338: 359,
 339: 360,
 340: 361,
 341: 362,
 342: 363,
 343: 364,
 344: 365,
 345: 366,
 346: 367,
 347: 368,
 348: 369,
 349: 370,
 350: 371,
 351: 372,
 352: 374,
 353: 375,
 354: 376,
 355: 377,
 356: 378,
 357: 380,
 358: 382,
 359: 383,
 360: 385,
 361: 386,
 362: 387,
 363: 388,
 364: 390,
 365: 391,
 366: 392,
 367: 393,
 368: 394,
 369: 395,
 370: 396,
 371: 397,
 372: 398,
 373: 399,
 374: 400,
 375: 401,
 376: 402,
 377: 403,
 378: 404,
 379: 405,
 380: 406,
 381: 407,
 382: 408,
 383: 409,
 384: 410,
 385: 411,
 386: 412,
 387: 413,
 388: 414,
 389: 415,
 390: 416,
 391: 417,
 392: 418,
 393: 419,
 394: 420,
 395: 421,
 396: 423,
 397: 424,
 398: 425,
 399: 426,
 400: 427,
 401: 428,
 402: 430,
 403: 431,
 404: 432,
 405: 433,
 406: 434,
 407: 435,
 408: 436,
 409: 437,
 410: 438,
 411: 439,
 412: 440,
 413: 441,
 414: 442,
 415: 443,
 416: 444,
 417: 446,
 418: 447,
 419: 449,
 420: 450,
 421: 451,
 422: 452,
 423: 453,
 424: 454,
 425: 455,
 426: 456,
 427: 457,
 428: 458,
 429: 459,
 430: 460,
 431: 461,
 432: 462,
 433: 463,
 434: 464,
 435: 465,
 436: 466,
 437: 467,
 438: 468,
 439: 469,
 440: 470,
 441: 471,
 442: 472,
 443: 473,
 444: 474,
 445: 475,
 446: 476,
 447: 477,
 448: 478,
 449: 479,
 450: 480,
 451: 481,
 452: 482,
 453: 484,
 454: 485,
 455: 486,
 456: 487,
 457: 488,
 458: 489,
 459: 490,
 460: 491,
 461: 492,
 462: 493,
 463: 494,
 464: 495,
 465: 496,
 466: 497,
 467: 498,
 468: 499,
 469: 500,
 470: 501,
 471: 502,
 472: 503,
 473: 504,
 474: 506,
 475: 507,
 476: 508,
 477: 509,
 478: 510,
 479: 511,
 480: 512,
 481: 513,
 482: 514,
 483: 515,
 484: 516,
 485: 517,
 486: 518,
 487: 519,
 488: 520,
 489: 521,
 490: 523,
 491: 525,
 492: 526,
 493: 527,
 494: 529,
 495: 530,
 496: 531,
 497: 532,
 498: 533,
 499: 534,
 500: 535,
 501: 536,
 502: 537,
 503: 538,
 504: 539,
 505: 540,
 506: 541,
 507: 542,
 508: 543,
 509: 544,
 510: 545,
 511: 546,
 512: 547,
 513: 548,
 514: 549,
 515: 550,
 516: 551,
 517: 552,
 518: 553,
 519: 555,
 520: 556,
 521: 557,
 522: 558,
 523: 559,
 524: 560,
 525: 561,
 526: 562,
 527: 563,
 528: 565,
 529: 566,
 530: 567,
 531: 568,
 532: 569,
 533: 570,
 534: 571,
 535: 572,
 536: 573,
 537: 574,
 538: 575,
 539: 576,
 540: 577,
 541: 578,
 542: 579,
 543: 580,
 544: 581,
 545: 582,
 546: 583,
 547: 584,
 548: 585,
 549: 586,
 550: 587,
 551: 589,
 552: 590,
 553: 592,
 554: 593,
 555: 594,
 556: 595,
 557: 596,
 558: 598,
 559: 601,
 560: 602,
 561: 603,
 562: 604,
 563: 605,
 564: 606,
 565: 607,
 566: 608,
 567: 609,
 568: 611,
 569: 612,
 570: 613,
 571: 614,
 572: 615,
 573: 616,
 574: 617,
 575: 618,
 576: 619,
 577: 620,
 578: 621,
 579: 622,
 580: 623,
 581: 624,
 582: 625,
 583: 627,
 584: 628,
 585: 629,
 586: 631,
 587: 632,
 588: 633,
 589: 634,
 590: 635,
 591: 636,
 592: 637,
 593: 638,
 594: 639,
 595: 640,
 596: 641,
 597: 642,
 598: 643,
 599: 644,
 600: 645,
 601: 646,
 602: 647,
 603: 649,
 604: 650,
 605: 651,
 606: 652,
 607: 654,
 608: 655,
 609: 656,
 610: 657,
 611: 658,
 612: 659,
 613: 660,
 614: 661,
 615: 662,
 616: 663,
 617: 664,
 618: 665,
 619: 666,
 620: 667,
 621: 668,
 622: 669,
 623: 670,
 624: 671,
 625: 672,
 626: 673,
 627: 674,
 628: 675,
 629: 676,
 630: 677,
 631: 678,
 632: 679,
 633: 680,
 634: 681,
 635: 682,
 636: 683,
 637: 684,
 638: 685,
 639: 686,
 640: 687,
 641: 688,
 642: 689,
 643: 690,
 644: 691,
 645: 692,
 646: 693,
 647: 694,
 648: 695,
 649: 696,
 650: 697,
 651: 698,
 652: 699,
 653: 700,
 654: 701,
 655: 702,
 656: 703,
 657: 704,
 658: 705,
 659: 706,
 660: 707,
 661: 708,
 662: 709,
 663: 710,
 664: 711,
 665: 712,
 666: 713,
 667: 714,
 668: 715,
 669: 716,
 670: 717,
 671: 718,
 672: 719,
 673: 720,
 674: 721,
 675: 722,
 676: 723,
 677: 725,
 678: 726,
 679: 727,
 680: 728,
 681: 729,
 682: 730,
 683: 731,
 684: 732,
 685: 733,
 686: 734,
 687: 735,
 688: 736,
 689: 737,
 690: 738,
 691: 739,
 692: 741,
 693: 742,
 694: 743,
 695: 744,
 696: 745,
 697: 746,
 698: 747,
 699: 749,
 700: 750,
 701: 751,
 702: 752,
 703: 753,
 704: 754,
 705: 756,
 706: 757,
 707: 758,
 708: 759,
 709: 760,
 710: 761,
 711: 762,
 712: 763,
 713: 764,
 714: 765,
 715: 767,
 716: 768,
 717: 769,
 718: 770,
 719: 771,
 720: 772,
 721: 773,
 722: 776,
 723: 777,
 724: 778,
 725: 779,
 726: 780,
 727: 781,
 728: 782,
 729: 784,
 730: 785,
 731: 786,
 732: 787,
 733: 788,
 734: 789,
 735: 790,
 736: 791,
 737: 792,
 738: 793,
 739: 794,
 740: 795,
 741: 797,
 742: 798,
 743: 799,
 744: 800,
 745: 801,
 746: 802,
 747: 804,
 748: 805,
 749: 806,
 750: 807,
 751: 808,
 752: 809,
 753: 810,
 754: 812,
 755: 813,
 756: 814,
 757: 815,
 758: 816,
 759: 817,
 760: 818,
 761: 819,
 762: 820,
 763: 821,
 764: 822,
 765: 823,
 766: 824,
 767: 825,
 768: 826,
 769: 827,
 770: 828,
 771: 829,
 772: 830,
 773: 831,
 774: 832,
 775: 834,
 776: 835,
 777: 836,
 778: 837,
 779: 838,
 780: 839,
 781: 840,
 782: 841,
 783: 842,
 784: 843,
 785: 844,
 786: 845,
 787: 846,
 788: 847,
 789: 848,
 790: 849,
 791: 850,
 792: 851,
 793: 852,
 794: 853,
 795: 854,
 796: 855,
 797: 856,
 798: 858,
 799: 859,
 800: 860,
 801: 861,
 802: 862,
 803: 863,
 804: 864,
 805: 865,
 806: 868,
 807: 869,
 808: 870,
 809: 871,
 810: 873,
 811: 874,
 812: 875,
 813: 876,
 814: 877,
 815: 878,
 816: 881,
 817: 882,
 818: 884,
 819: 885,
 820: 886,
 821: 887,
 822: 888,
 823: 889,
 824: 890,
 825: 891,
 826: 893,
 827: 895,
 828: 896,
 829: 897,
 830: 898,
 831: 899,
 832: 900,
 833: 903,
 834: 904,
 835: 905,
 836: 906,
 837: 907,
 838: 908,
 839: 909,
 840: 910,
 841: 911,
 842: 912,
 843: 913,
 844: 914,
 845: 915,
 846: 916,
 847: 917,
 848: 919,
 849: 920,
 850: 921,
 851: 922,
 852: 924,
 853: 925,
 854: 926,
 855: 927,
 856: 928,
 857: 929,
 858: 930,
 859: 931,
 860: 932,
 861: 933,
 862: 934,
 863: 935,
 864: 936,
 865: 938,
 866: 939,
 867: 940,
 868: 941,
 869: 942,
 870: 943,
 871: 946,
 872: 948,
 873: 949,
 874: 950,
 875: 951,
 876: 952,
 877: 953,
 878: 954,
 879: 955,
 880: 957,
 881: 958,
 882: 959,
 883: 960,
 884: 961,
 885: 962,
 886: 963,
 887: 964,
 888: 965,
 889: 966,
 890: 967,
 891: 968,
 892: 969,
 893: 971,
 894: 972,
 895: 975,
 896: 976,
 897: 977,
 898: 978,
 899: 979,
 900: 980,
 901: 981,
 902: 982,
 903: 984,
 904: 985,
 905: 986,
 906: 987,
 907: 989,
 908: 990,
 909: 991,
 910: 993,
 911: 994,
 912: 995,
 913: 996,
 914: 997,
 915: 998,
 916: 999,
 917: 1001,
 918: 1002,
 919: 1003,
 920: 1004,
 921: 1005,
 922: 1006,
 923: 1007,
 924: 1008,
 925: 1009,
 926: 1010,
 927: 1011,
 928: 1012,
 929: 1013,
 930: 1014,
 931: 1015,
 932: 1016,
 933: 1017,
 934: 1018,
 935: 1019,
 936: 1020,
 937: 1021,
 938: 1022,
 939: 1023,
 940: 1024,
 941: 1025,
 942: 1026,
 943: 1027,
 944: 1028,
 945: 1029,
 946: 1030,
 947: 1032,
 948: 1033,
 949: 1034,
 950: 1035,
 951: 1036,
 952: 1037,
 953: 1038,
 954: 1039,
 955: 1040,
 956: 1041,
 957: 1042,
 958: 1044,
 959: 1046,
 960: 1047,
 961: 1049,
 962: 1050,
 963: 1051,
 964: 1052,
 965: 1053,
 966: 1054,
 967: 1055,
 968: 1056,
 969: 1057,
 970: 1058,
 971: 1060,
 972: 1061,
 973: 1062,
 974: 1063,
 975: 1064,
 976: 1065,
 977: 1067,
 978: 1068,
 979: 1069,
 980: 1070,
 981: 1071,
 982: 1072,
 983: 1073,
 984: 1074,
 985: 1075,
 986: 1076,
 987: 1078,
 988: 1079,
 989: 1080,
 990: 1081,
 991: 1082,
 992: 1083,
 993: 1084,
 994: 1085,
 995: 1086,
 996: 1087,
 997: 1088,
 998: 1089,
 999: 1090,
 1000: 1091,
 ...}

In [18]:
artist_id_to_ordered_id = {}
ordered_id_to_artist_id = {}
for idx,artist_id in enumerate(artist_user_df['artistID'].unique()) : 
    artist_id_to_ordered_id[artist_id] = idx+1
    ordered_id_to_artist_id[idx+1] = artist_id

In [19]:
import joblib 


joblib.dump(user_id_to_ordered_id,'../mapping/user_id_to_ordered_id.pkl')
joblib.dump(ordered_id_to_user_id,'../mapping/ordered_id_to_user_id.pkl')
joblib.dump(artist_id_to_ordered_id,'../mapping/artist_id_to_ordered_id.pkl')
joblib.dump(ordered_id_to_artist_id,'../mapping/ordered_id_to_artist_id.pkl')

['../mapping/ordered_id_to_artist_id.pkl']

## Mapping userID and artistID

In [20]:
mapped_user_artist_df = artist_user_df.copy()

In [21]:
mapped_user_artist_df.userID = mapped_user_artist_df.userID.map(user_id_to_ordered_id)
mapped_user_artist_df.artistID = mapped_user_artist_df.artistID.map(artist_id_to_ordered_id)

In [22]:
mapped_user_artist_df

       userID  artistID  weight
0           1         1   13883
1           1         2   11690
2           1         3   11351
3           1         4   10300
4           1         5    8983
...       ...       ...     ...
92829    1892     17628     337
92830    1892     17629     297
92831    1892     17630     281
92832    1892     17631     280
92833    1892     17632     263

[92834 rows x 3 columns]

## Create Utility Matrix

In [23]:
from scipy.sparse import coo_matrix
"""
From Documentation 
Constructing a matrix using ijv format

row  = np.array([0, 3, 1, 0])
col  = np.array([0, 3, 1, 2])
data = np.array([4, 5, 7, 9])
coo_array((data, (row, col)), shape=(4, 4)).toarray()
array([[4, 0, 9, 0],
       [0, 7, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 5]])
"""
row = mapped_user_artist_df.userID.values
col = mapped_user_artist_df.artistID.values
data = mapped_user_artist_df.weight.values


implicit_utility = coo_matrix((data,(row,col)))
implicit_utility = implicit_utility.tocsr()

In [24]:
def create_utility_matrix(utility_df,data,row_name,col_name,value_name) : 
    """_summary_

    Args:
        data (_type_): _description_
        row_name (_type_): _description_
        col_name (_type_): _description_
        value_name (_type_): _description_
    """
    ## TODO : add to utils package. 
    row = utility_df[row_name].values
    col = utility_df[col_name].values
    data = utility_df[value_name].values


    utility_matrix = coo_matrix((data,(row,col)))
    utility_matrix = implicit_utility.tocsr()
    return utility_matrix

In [25]:
print(implicit_utility)

  (1, 1)	13883
  (1, 2)	11690
  (1, 3)	11351
  (1, 4)	10300
  (1, 5)	8983
  (1, 6)	6152
  (1, 7)	5955
  (1, 8)	4616
  (1, 9)	4337
  (1, 10)	4147
  (1, 11)	3923
  (1, 12)	3782
  (1, 13)	3735
  (1, 14)	3644
  (1, 15)	3579
  (1, 16)	3312
  (1, 17)	3301
  (1, 18)	2927
  (1, 19)	2720
  (1, 20)	2686
  (1, 21)	2654
  (1, 22)	2619
  (1, 23)	2584
  (1, 24)	2547
  (1, 25)	2397
  :	:
  (1892, 7994)	284
  (1892, 7996)	650
  (1892, 7997)	456
  (1892, 7998)	1068
  (1892, 8000)	626
  (1892, 8001)	613
  (1892, 8006)	655
  (1892, 8018)	640
  (1892, 8175)	232
  (1892, 8179)	429
  (1892, 8181)	607
  (1892, 8183)	724
  (1892, 9414)	793
  (1892, 9602)	228
  (1892, 12990)	278
  (1892, 12992)	346
  (1892, 15543)	443
  (1892, 17625)	705
  (1892, 17626)	535
  (1892, 17627)	758
  (1892, 17628)	337
  (1892, 17629)	297
  (1892, 17630)	281
  (1892, 17631)	280
  (1892, 17632)	263

## Split Dataset 
Training, Validation, and Testing

In [5]:
from implicit.evaluation import train_test_split

ModuleNotFoundError: No module named 'implicit'

In [27]:
implicit_utility_coo = implicit_utility.tocoo()


train_data,test_data = train_test_split(ratings=implicit_utility_coo,train_percentage=0.8)
train_data_coo = train_data.tocoo()

train_data,val_data = train_test_split(ratings=train_data_coo,train_percentage=0.8)

In [28]:
def generate_train_val_test(utility_matrix) : 
    """_summary_

    Args:
        utility_matrix (_type_): csr matrix
    """
    utility_matrix = implicit_utility.tocoo()


    train_data,test_data = train_test_split(ratings=utility_matrix,train_percentage=0.8)
    train_data_coo = train_data.tocoo()

    train_data,val_data = train_test_split(ratings=utility_matrix,train_percentage=0.8)
    
    return train_data,val_data,test_data

In [29]:
(implicit_utility_coo.nnz)

92834

In [30]:
train_data.nnz

59378

In [31]:
val_data.nnz

14973

In [32]:
test_data.nnz

18483

## Fit model on training data

### ALS Approach

In [34]:
from implicit.als import AlternatingLeastSquares
from implicit.nearest_neighbours import bm25_weight,tfidf_weight



model_als = AlternatingLeastSquares(factors=100)
model_als.fit(train_data)

  0%|          | 0/15 [00:00<?, ?it/s]100%|██████████| 15/15 [00:08<00:00,  1.78it/s]

(array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0], dtype=int32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32))

### Bayesian Personalized Ranking

In [36]:
from implicit.bpr import BayesianPersonalizedRanking

model_bpr = BayesianPersonalizedRanking(factors=100)
model_bpr.fit(train_data)

/home/fakhri/pacmann_project/recsys_project/lib/python3.10/site-packages/implicit/utils.py:138: ParameterWarning: Method expects CSR input, and was passed coo_matrix instead. Converting to CSR took 0.0007708072662353516 seconds
  warnings.warn(
100%|██████████| 100/100 [00:02<00:00, 33.34it/s, train_auc=87.98%, skipped=3.10%]

### Logistic Matrix Factorization

In [37]:
from implicit.lmf import LogisticMatrixFactorization

model_logmat = LogisticMatrixFactorization(factors=100)
model_logmat.fit(train_data)

/home/fakhri/pacmann_project/recsys_project/lib/python3.10/site-packages/implicit/utils.py:138: ParameterWarning: Method expects CSR input, and was passed coo_matrix instead. Converting to CSR took 0.0005617141723632812 seconds
  warnings.warn(
 60%|██████    | 18/30 [00:01<00:00, 12.46it/s]100%|██████████| 30/30 [00:02<00:00, 12.42it/s]

### Hybrid Approach

## Find Best Model Based on Prediction on Validation Set

In [38]:
method_list = [func for func in dir(model_bpr) if callable(getattr(model_bpr, func)) and not func.startswith("__")]

In [39]:
prediction_bpr_val = model_bpr.recommend_all(val_data)

In [40]:
from implicit.evaluation import ranking_metrics_at_k


metrics_als = ranking_metrics_at_k(model=model_als,
                                   train_user_items=train_data,
                                   test_user_items=val_data)

100%|██████████| 1884/1884 [00:00<00:00, 5093.67it/s]

In [41]:
metrics_bpr = ranking_metrics_at_k(model=model_bpr,
                                   train_user_items=train_data,
                                   test_user_items=val_data)

100%|██████████| 1884/1884 [00:00<00:00, 4768.26it/s]

In [42]:
metrics_lmf = ranking_metrics_at_k(model=model_logmat,
                                   train_user_items=train_data,
                                   test_user_items=val_data)

100%|██████████| 1884/1884 [00:00<00:00, 4818.95it/s]

In [43]:
metrics_als_df = pd.DataFrame(metrics_als,index=[0])
metrics_als_df['model'] = 'AlternatingLeastSquares'

In [44]:
metrics_als_df

   precision       map      ndcg       auc                    model
0   0.135773  0.062366  0.134182  0.565975  AlternatingLeastSquares

In [45]:
metrics_bpr_df  = pd.DataFrame(metrics_bpr,index=[0])
metrics_bpr_df
metrics_bpr_df['model'] = 'BayesianPersonalizedRanking'

In [46]:
metrics_lmf_df  = pd.DataFrame(metrics_lmf,index=[0])
metrics_lmf_df['model'] = 'LogisticMatrixFactorization'

In [49]:
model_selection_df = pd.concat([metrics_als_df,metrics_bpr_df,metrics_lmf_df],axis=0)
model_selection_df

   precision       map      ndcg       auc                        model
0   0.135773  0.062366  0.134182  0.565975      AlternatingLeastSquares
0   0.112814  0.053603  0.115200  0.553911  BayesianPersonalizedRanking
0   0.014199  0.004576  0.013120  0.506782  LogisticMatrixFactorization

## Hyperparameter Tuning

Use optuna on 5 Fold Cross Validation

In [ ]:
tra

In [52]:
#create cross validation helper 

from sklearn.model_selection import KFold

Fold :  1
Train Index :  [ 379  380  381 ... 1890 1891 1892]
Test Idx [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251
 252 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269
 270 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287
 288 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305
 306 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323
 324 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341
 342 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359
 360 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377
 378]
Fold :  2
Train Index :  [   0    1    2 ... 1890 1891 1892]
Test Idx [379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395 396
 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414
 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431 432
 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449 450
 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467 468
 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485 486
 487 488 489 490 491 492 493 494 495 496 497 498 499 500 501 502 503 504
 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521 522
 523 524 525 526 527 528 529 530 531 532 533 534 535 536 537 538 539 540
 541 542 543 544 545 546 547 548 549 550 551 552 553 554 555 556 557 558
 559 560 561 562 563 564 565 566 567 568 569 570 571 572 573 574 575 576
 577 578 579 580 581 582 583 584 585 586 587 588 589 590 591 592 593 594
 595 596 597 598 599 600 601 602 603 604 605 606 607 608 609 610 611 612
 613 614 615 616 617 618 619 620 621 622 623 624 625 626 627 628 629 630
 631 632 633 634 635 636 637 638 639 640 641 642 643 644 645 646 647 648
 649 650 651 652 653 654 655 656 657 658 659 660 661 662 663 664 665 666
 667 668 669 670 671 672 673 674 675 676 677 678 679 680 681 682 683 684
 685 686 687 688 689 690 691 692 693 694 695 696 697 698 699 700 701 702
 703 704 705 706 707 708 709 710 711 712 713 714 715 716 717 718 719 720
 721 722 723 724 725 726 727 728 729 730 731 732 733 734 735 736 737 738
 739 740 741 742 743 744 745 746 747 748 749 750 751 752 753 754 755 756
 757]
Fold :  3
Train Index :  [   0    1    2 ... 1890 1891 1892]
Test Idx [ 758  759  760  761  762  763  764  765  766  767  768  769  770  771
  772  773  774  775  776  777  778  779  780  781  782  783  784  785
  786  787  788  789  790  791  792  793  794  795  796  797  798  799
  800  801  802  803  804  805  806  807  808  809  810  811  812  813
  814  815  816  817  818  819  820  821  822  823  824  825  826  827
  828  829  830  831  832  833  834  835  836  837  838  839  840  841
  842  843  844  845  846  847  848  849  850  851  852  853  854  855
  856  857  858  859  860  861  862  863  864  865  866  867  868  869
  870  871  872  873  874  875  876  877  878  879  880  881  882  883
  884  885  886  887  888  889  890  891  892  893  894  895  896  897
  898  899  900  901  902  903  904  905  906  907  908  909  910  911
  912  913  914  915  916  917  918  919  920  921  922  923  924  925
  926  927  928  929  930  931  932  933  934  935  936  937  938  939
  940  941  942  943  944  945  946  947  948  949  950  951  952  953
  954  955  956  957  958  959  960  961  962  963  964  965  966  967
  968  969  970  971  972  973  974  975  976  977  978  979  980  981
  982  983  984  985  986  987  988  989  990  991  992  993  994  995
  996  997  998  999 1000 1001 1002 1003 1004 1005 1006 1007 1008 1009
 1010 1011 1012 1013 1014 1015 1016 1017 1018 1019 1020 1021 1022 1023
 1024 1025 1026 1027 1028 1029 1030 1031 1032 1033 1034 1035 1036 1037
 1038 1039 1040 1041 1042 1043 1044 1045 1046 1047 1048 1049 1050 1051
 1052 1053 1054 1055 1056 1057 1058 1059 1060 1061 1062 1063 1064 1065
 1066 1067 1068 1069 1070 1071 1072 1073 1074 1075 1076 1077 1078 1079
 1080 1081 1082 1083 1084 1085 1086 1087 1088 1089 1090 1091 1092 1093
 1094 1095 1096 1097 1098 1099 1100 1101 1102 1103 1104 1105 1106 1107
 1108 1109 1110 1111 1112 1113 1114 1115 1116 1117 1118 1119 1120 1121
 1122 1123 1124 1125 1126 1127 1128 1129 1130 1131 1132 1133 1134 1135
 1136]
Fold :  4
Train Index :  [   0    1    2 ... 1890 1891 1892]
Test Idx [1137 1138 1139 1140 1141 1142 1143 1144 1145 1146 1147 1148 1149 1150
 1151 1152 1153 1154 1155 1156 1157 1158 1159 1160 1161 1162 1163 1164
 1165 1166 1167 1168 1169 1170 1171 1172 1173 1174 1175 1176 1177 1178
 1179 1180 1181 1182 1183 1184 1185 1186 1187 1188 1189 1190 1191 1192
 1193 1194 1195 1196 1197 1198 1199 1200 1201 1202 1203 1204 1205 1206
 1207 1208 1209 1210 1211 1212 1213 1214 1215 1216 1217 1218 1219 1220
 1221 1222 1223 1224 1225 1226 1227 1228 1229 1230 1231 1232 1233 1234
 1235 1236 1237 1238 1239 1240 1241 1242 1243 1244 1245 1246 1247 1248
 1249 1250 1251 1252 1253 1254 1255 1256 1257 1258 1259 1260 1261 1262
 1263 1264 1265 1266 1267 1268 1269 1270 1271 1272 1273 1274 1275 1276
 1277 1278 1279 1280 1281 1282 1283 1284 1285 1286 1287 1288 1289 1290
 1291 1292 1293 1294 1295 1296 1297 1298 1299 1300 1301 1302 1303 1304
 1305 1306 1307 1308 1309 1310 1311 1312 1313 1314 1315 1316 1317 1318
 1319 1320 1321 1322 1323 1324 1325 1326 1327 1328 1329 1330 1331 1332
 1333 1334 1335 1336 1337 1338 1339 1340 1341 1342 1343 1344 1345 1346
 1347 1348 1349 1350 1351 1352 1353 1354 1355 1356 1357 1358 1359 1360
 1361 1362 1363 1364 1365 1366 1367 1368 1369 1370 1371 1372 1373 1374
 1375 1376 1377 1378 1379 1380 1381 1382 1383 1384 1385 1386 1387 1388
 1389 1390 1391 1392 1393 1394 1395 1396 1397 1398 1399 1400 1401 1402
 1403 1404 1405 1406 1407 1408 1409 1410 1411 1412 1413 1414 1415 1416
 1417 1418 1419 1420 1421 1422 1423 1424 1425 1426 1427 1428 1429 1430
 1431 1432 1433 1434 1435 1436 1437 1438 1439 1440 1441 1442 1443 1444
 1445 1446 1447 1448 1449 1450 1451 1452 1453 1454 1455 1456 1457 1458
 1459 1460 1461 1462 1463 1464 1465 1466 1467 1468 1469 1470 1471 1472
 1473 1474 1475 1476 1477 1478 1479 1480 1481 1482 1483 1484 1485 1486
 1487 1488 1489 1490 1491 1492 1493 1494 1495 1496 1497 1498 1499 1500
 1501 1502 1503 1504 1505 1506 1507 1508 1509 1510 1511 1512 1513 1514]
Fold :  5
Train Index :  [   0    1    2 ... 1512 1513 1514]
Test Idx [1515 1516 1517 1518 1519 1520 1521 1522 1523 1524 1525 1526 1527 1528
 1529 1530 1531 1532 1533 1534 1535 1536 1537 1538 1539 1540 1541 1542
 1543 1544 1545 1546 1547 1548 1549 1550 1551 1552 1553 1554 1555 1556
 1557 1558 1559 1560 1561 1562 1563 1564 1565 1566 1567 1568 1569 1570
 1571 1572 1573 1574 1575 1576 1577 1578 1579 1580 1581 1582 1583 1584
 1585 1586 1587 1588 1589 1590 1591 1592 1593 1594 1595 1596 1597 1598
 1599 1600 1601 1602 1603 1604 1605 1606 1607 1608 1609 1610 1611 1612
 1613 1614 1615 1616 1617 1618 1619 1620 1621 1622 1623 1624 1625 1626
 1627 1628 1629 1630 1631 1632 1633 1634 1635 1636 1637 1638 1639 1640
 1641 1642 1643 1644 1645 1646 1647 1648 1649 1650 1651 1652 1653 1654
 1655 1656 1657 1658 1659 1660 1661 1662 1663 1664 1665 1666 1667 1668
 1669 1670 1671 1672 1673 1674 1675 1676 1677 1678 1679 1680 1681 1682
 1683 1684 1685 1686 1687 1688 1689 1690 1691 1692 1693 1694 1695 1696
 1697 1698 1699 1700 1701 1702 1703 1704 1705 1706 1707 1708 1709 1710
 1711 1712 1713 1714 1715 1716 1717 1718 1719 1720 1721 1722 1723 1724
 1725 1726 1727 1728 1729 1730 1731 1732 1733 1734 1735 1736 1737 1738
 1739 1740 1741 1742 1743 1744 1745 1746 1747 1748 1749 1750 1751 1752
 1753 1754 1755 1756 1757 1758 1759 1760 1761 1762 1763 1764 1765 1766
 1767 1768 1769 1770 1771 1772 1773 1774 1775 1776 1777 1778 1779 1780
 1781 1782 1783 1784 1785 1786 1787 1788 1789 1790 1791 1792 1793 1794
 1795 1796 1797 1798 1799 1800 1801 1802 1803 1804 1805 1806 1807 1808
 1809 1810 1811 1812 1813 1814 1815 1816 1817 1818 1819 1820 1821 1822
 1823 1824 1825 1826 1827 1828 1829 1830 1831 1832 1833 1834 1835 1836
 1837 1838 1839 1840 1841 1842 1843 1844 1845 1846 1847 1848 1849 1850
 1851 1852 1853 1854 1855 1856 1857 1858 1859 1860 1861 1862 1863 1864
 1865 1866 1867 1868 1869 1870 1871 1872 1873 1874 1875 1876 1877 1878
 1879 1880 1881 1882 1883 1884 1885 1886 1887 1888 1889 1890 1891 1892]

In [59]:
import optuna 
from scipy.sparse import csr_matrix

from implicit.evaluation import ndcg_at_k

train_data,test_data = train_test_split(ratings=implicit_utility_coo,train_percentage=0.8)
train_utility = train_data.tocoo()
def objective(trial):
    #parameter recommendation 
    
    #discrete parameter
    factors_param = trial.suggest_int('number_of_factors',low=100,high=500,step=100) 
    
    #continous parameter
    alpha_param = trial.suggest_loguniform('alpha_weight',low=0.01,high=1.0)
    regularization_param = trial.suggest_loguniform('regularization',low=0.01,high=0.2)

    #define cross validation 

    
    #cross validation 
    fold = KFold(5)

    ndcg_sum = 0
    for idx,(train_idx,test_idx) in enumerate(fold.split(train_utility)) : 
       
        model_als_tuning = AlternatingLeastSquares(factors=factors_param,
                                            regularization=regularization_param,
                                            alpha=alpha_param)
        train = csr_matrix((train_utility.data[train_idx],
                        (train_utility.row[train_idx], train_utility.col[train_idx])),
                        shape=train_utility.shape, dtype=train_utility.dtype)

        test = csr_matrix((train_utility.data[test_idx],
                        (train_utility.row[test_idx], train_utility.col[test_idx])),
                        shape=train_utility.shape, dtype=train_utility.dtype)
        model_als_tuning.fit(train)
        ndcg_at_fold = ndcg_at_k(model=model_als_tuning,
                  train_user_items=train,
                  test_user_items=test,K=10)
        ndcg_sum +=ndcg_at_fold
        
        #logging the tuning process 

    #add negative to minimize function like Negative Log LikeLihood --> gradient descent
    ndcg_avg = -(ndcg_sum / 5)
    print(f'''Fold : {idx+1}
         Average NDCG : {ndcg_avg}
        
        
        
        ''')
    return ndcg_avg

In [60]:
#create study object 
study=optuna.create_study(direction='minimize')
study.optimize(objective, n_trials=100)

[I 2023-07-08 22:15:02,824] A new study created in memory with name: no-name-2d8abc33-b525-4e6d-87df-dabbcfeeccc8
/tmp/ipykernel_1391/1203725529.py:15: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  alpha_param = trial.suggest_loguniform('alpha_weight',low=0.01,high=1.0)
/tmp/ipykernel_1391/1203725529.py:16: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  regularization_param = trial.suggest_loguniform('regularization',low=0.01,high=0.2)
100%|██████████| 15/15 [00:01<00:00,  8.53it/s]
100%|██████████| 10/10 [00:00<00:00, 2240.91it/s]
100%|██████████| 15/15 [00:01<00:00, 10.38it/s]
100%|██████████| 10/10 [00:00<00:00, 2329.65it/s]
100%|██████████| 15/15 [00:01<00:00, 10.48it/s]
100%|██████████| 10/10 [00:00<00:00, 2469.85it/s]
100%|██████████| 15/15 [00:01<00:00, 10.89it/s]
100%|██████████| 11/11 [00:00<00:00, 2500.26it/s]
100%|██████████| 15/15 [00:01<00:00,  9.99it/s]
100%|██████████| 10/10 [00:00<00:00, 1901.23it/s]
[I 2023-07-08 22:15:10,890] Trial 0 finished with value: -0.0880229712191308 and parameters: {'number_of_factors': 300, 'alpha_weight': 0.2184051697483856, 'regularization': 0.036642040880920254}. Best is trial 0 with value: -0.0880229712191308.

Fold : 5
         Average NDCG : -0.0880229712191308

100%|██████████| 15/15 [00:02<00:00,  6.01it/s]
100%|██████████| 10/10 [00:00<00:00, 1555.35it/s]
100%|██████████| 15/15 [00:02<00:00,  6.37it/s]
100%|██████████| 10/10 [00:00<00:00, 1455.60it/s]
100%|██████████| 15/15 [00:02<00:00,  6.19it/s]
100%|██████████| 10/10 [00:00<00:00, 1656.26it/s]
100%|██████████| 15/15 [00:02<00:00,  6.39it/s]
100%|██████████| 11/11 [00:00<00:00, 1706.58it/s]
100%|██████████| 15/15 [00:02<00:00,  6.37it/s]
100%|██████████| 10/10 [00:00<00:00, 1569.14it/s]
[I 2023-07-08 22:15:23,749] Trial 1 finished with value: -0.08740949303670197 and parameters: {'number_of_factors': 500, 'alpha_weight': 0.013321148113008777, 'regularization': 0.013170011165423542}. Best is trial 0 with value: -0.0880229712191308.

Fold : 5
         Average NDCG : -0.08740949303670197

100%|██████████| 15/15 [00:01<00:00, 13.67it/s]
100%|██████████| 10/10 [00:00<00:00, 4765.17it/s]
100%|██████████| 15/15 [00:01<00:00, 14.00it/s]
100%|██████████| 10/10 [00:00<00:00, 4281.65it/s]
100%|██████████| 15/15 [00:01<00:00, 13.77it/s]
100%|██████████| 10/10 [00:00<00:00, 4291.29it/s]
100%|██████████| 15/15 [00:01<00:00, 13.79it/s]
100%|██████████| 11/11 [00:00<00:00, 3515.49it/s]
100%|██████████| 15/15 [00:01<00:00, 13.12it/s]
100%|██████████| 10/10 [00:00<00:00, 3988.88it/s]
[I 2023-07-08 22:15:29,396] Trial 2 finished with value: -0.07923520040328755 and parameters: {'number_of_factors': 100, 'alpha_weight': 0.05332152594893357, 'regularization': 0.011282151290191158}. Best is trial 0 with value: -0.0880229712191308.

Fold : 5
         Average NDCG : -0.07923520040328755

100%|██████████| 15/15 [00:01<00:00, 11.50it/s]
100%|██████████| 10/10 [00:00<00:00, 2460.87it/s]
100%|██████████| 15/15 [00:01<00:00, 11.44it/s]
100%|██████████| 10/10 [00:00<00:00, 2495.87it/s]
100%|██████████| 15/15 [00:01<00:00, 10.90it/s]
100%|██████████| 10/10 [00:00<00:00, 2350.28it/s]
100%|██████████| 15/15 [00:01<00:00, 11.32it/s]
100%|██████████| 11/11 [00:00<00:00, 2601.34it/s]
100%|██████████| 15/15 [00:01<00:00, 11.33it/s]
100%|██████████| 10/10 [00:00<00:00, 2453.24it/s]
[I 2023-07-08 22:15:36,577] Trial 3 finished with value: -0.08331059520971046 and parameters: {'number_of_factors': 300, 'alpha_weight': 0.08782138548212011, 'regularization': 0.020393955951092533}. Best is trial 0 with value: -0.0880229712191308.

Fold : 5
         Average NDCG : -0.08331059520971046

100%|██████████| 15/15 [00:01<00:00, 11.38it/s]
100%|██████████| 10/10 [00:00<00:00, 2408.44it/s]
100%|██████████| 15/15 [00:01<00:00, 11.49it/s]
100%|██████████| 10/10 [00:00<00:00, 2116.41it/s]
100%|██████████| 15/15 [00:01<00:00, 11.51it/s]
100%|██████████| 10/10 [00:00<00:00, 2403.47it/s]
100%|██████████| 15/15 [00:01<00:00, 11.31it/s]
100%|██████████| 11/11 [00:00<00:00, 2518.55it/s]
100%|██████████| 15/15 [00:01<00:00, 11.35it/s]
100%|██████████| 10/10 [00:00<00:00, 2405.82it/s]
[I 2023-07-08 22:15:43,700] Trial 4 finished with value: -0.08944185332973069 and parameters: {'number_of_factors': 300, 'alpha_weight': 0.8398683273206269, 'regularization': 0.055654821918804644}. Best is trial 4 with value: -0.08944185332973069.

Fold : 5
         Average NDCG : -0.08944185332973069

100%|██████████| 15/15 [00:01<00:00, 13.36it/s]
100%|██████████| 10/10 [00:00<00:00, 3542.19it/s]
100%|██████████| 15/15 [00:01<00:00, 13.60it/s]
100%|██████████| 10/10 [00:00<00:00, 3871.78it/s]
100%|██████████| 15/15 [00:01<00:00, 13.65it/s]
100%|██████████| 10/10 [00:00<00:00, 2811.95it/s]
100%|██████████| 15/15 [00:01<00:00, 13.53it/s]
100%|██████████| 11/11 [00:00<00:00, 4335.40it/s]
100%|██████████| 15/15 [00:01<00:00, 13.68it/s]
100%|██████████| 10/10 [00:00<00:00, 4327.15it/s]
[I 2023-07-08 22:15:49,384] Trial 5 finished with value: -0.08920199704516404 and parameters: {'number_of_factors': 100, 'alpha_weight': 0.22923324243753423, 'regularization': 0.014253883208376584}. Best is trial 4 with value: -0.08944185332973069.

Fold : 5
         Average NDCG : -0.08920199704516404

100%|██████████| 15/15 [00:02<00:00,  6.20it/s]
100%|██████████| 10/10 [00:00<00:00, 1657.83it/s]
100%|██████████| 15/15 [00:02<00:00,  6.38it/s]
100%|██████████| 10/10 [00:00<00:00, 1517.59it/s]
100%|██████████| 15/15 [00:02<00:00,  6.35it/s]
100%|██████████| 10/10 [00:00<00:00, 1503.55it/s]
100%|██████████| 15/15 [00:02<00:00,  6.32it/s]
100%|██████████| 11/11 [00:00<00:00, 1675.77it/s]
100%|██████████| 15/15 [00:02<00:00,  6.32it/s]
100%|██████████| 10/10 [00:00<00:00, 1670.90it/s]
[I 2023-07-08 22:16:02,134] Trial 6 finished with value: -0.08487743969998848 and parameters: {'number_of_factors': 500, 'alpha_weight': 0.06948907721070112, 'regularization': 0.010120405012867893}. Best is trial 4 with value: -0.08944185332973069.

Fold : 5
         Average NDCG : -0.08487743969998848

100%|██████████| 15/15 [00:01<00:00, 11.45it/s]
100%|██████████| 10/10 [00:00<00:00, 2214.05it/s]
100%|██████████| 15/15 [00:01<00:00, 11.56it/s]
100%|██████████| 10/10 [00:00<00:00, 2448.80it/s]
100%|██████████| 15/15 [00:01<00:00, 11.29it/s]
100%|██████████| 10/10 [00:00<00:00, 2515.78it/s]
100%|██████████| 15/15 [00:01<00:00, 11.60it/s]
100%|██████████| 11/11 [00:00<00:00, 2362.02it/s]
100%|██████████| 15/15 [00:01<00:00, 11.31it/s]
100%|██████████| 10/10 [00:00<00:00, 2494.09it/s]
[I 2023-07-08 22:16:09,242] Trial 7 finished with value: -0.0857141017009277 and parameters: {'number_of_factors': 300, 'alpha_weight': 0.07558320230512078, 'regularization': 0.08392540141156195}. Best is trial 4 with value: -0.08944185332973069.

Fold : 5
         Average NDCG : -0.0857141017009277

100%|██████████| 15/15 [00:01<00:00, 13.85it/s]
100%|██████████| 10/10 [00:00<00:00, 4170.53it/s]
100%|██████████| 15/15 [00:01<00:00, 13.35it/s]
100%|██████████| 10/10 [00:00<00:00, 3906.77it/s]
100%|██████████| 15/15 [00:01<00:00, 12.38it/s]
100%|██████████| 10/10 [00:00<00:00, 3784.11it/s]
100%|██████████| 15/15 [00:01<00:00, 13.34it/s]
100%|██████████| 11/11 [00:00<00:00, 3862.81it/s]
100%|██████████| 15/15 [00:01<00:00, 12.91it/s]
100%|██████████| 10/10 [00:00<00:00, 2465.79it/s]
[I 2023-07-08 22:16:15,102] Trial 8 finished with value: -0.09298798146942837 and parameters: {'number_of_factors': 100, 'alpha_weight': 0.6586826491423069, 'regularization': 0.06366855901772833}. Best is trial 8 with value: -0.09298798146942837.

Fold : 5
         Average NDCG : -0.09298798146942837

100%|██████████| 15/15 [00:01<00:00,  7.64it/s]
100%|██████████| 10/10 [00:00<00:00, 1866.54it/s]
100%|██████████| 15/15 [00:02<00:00,  7.39it/s]
100%|██████████| 10/10 [00:00<00:00, 1771.62it/s]
100%|██████████| 15/15 [00:01<00:00,  7.51it/s]
100%|██████████| 10/10 [00:00<00:00, 1863.56it/s]
100%|██████████| 15/15 [00:01<00:00,  7.60it/s]
100%|██████████| 11/11 [00:00<00:00, 2005.19it/s]
100%|██████████| 15/15 [00:01<00:00,  7.79it/s]
100%|██████████| 10/10 [00:00<00:00, 1754.13it/s]
[I 2023-07-08 22:16:25,653] Trial 9 finished with value: -0.08448240716978571 and parameters: {'number_of_factors': 400, 'alpha_weight': 0.013258897857556129, 'regularization': 0.029030636273663223}. Best is trial 8 with value: -0.09298798146942837.

Fold : 5
         Average NDCG : -0.08448240716978571

100%|██████████| 15/15 [00:01<00:00, 12.12it/s]
100%|██████████| 10/10 [00:00<00:00, 3212.06it/s]
100%|██████████| 15/15 [00:01<00:00, 12.45it/s]
100%|██████████| 10/10 [00:00<00:00, 2850.94it/s]
100%|██████████| 15/15 [00:01<00:00, 12.19it/s]
100%|██████████| 10/10 [00:00<00:00, 2677.33it/s]
100%|██████████| 15/15 [00:01<00:00, 12.42it/s]
100%|██████████| 11/11 [00:00<00:00, 3187.82it/s]
100%|██████████| 15/15 [00:01<00:00, 12.24it/s]
100%|██████████| 10/10 [00:00<00:00, 2971.31it/s]
[I 2023-07-08 22:16:32,026] Trial 10 finished with value: -0.09411844623683926 and parameters: {'number_of_factors': 200, 'alpha_weight': 0.9134804255211995, 'regularization': 0.18629452202985763}. Best is trial 10 with value: -0.09411844623683926.

Fold : 5
         Average NDCG : -0.09411844623683926

100%|██████████| 15/15 [00:01<00:00, 12.16it/s]
100%|██████████| 10/10 [00:00<00:00, 3136.87it/s]
100%|██████████| 15/15 [00:01<00:00, 12.24it/s]
100%|██████████| 10/10 [00:00<00:00, 2975.11it/s]
100%|██████████| 15/15 [00:01<00:00, 11.56it/s]
100%|██████████| 10/10 [00:00<00:00, 2793.78it/s]
100%|██████████| 15/15 [00:01<00:00, 11.82it/s]
100%|██████████| 11/11 [00:00<00:00, 3104.38it/s]
100%|██████████| 15/15 [00:01<00:00, 12.15it/s]
100%|██████████| 10/10 [00:00<00:00, 3116.36it/s]
[I 2023-07-08 22:16:38,556] Trial 11 finished with value: -0.09690212931297347 and parameters: {'number_of_factors': 200, 'alpha_weight': 0.815003150036171, 'regularization': 0.1897600098330393}. Best is trial 11 with value: -0.09690212931297347.

Fold : 5
         Average NDCG : -0.09690212931297347

100%|██████████| 15/15 [00:01<00:00, 11.65it/s]
100%|██████████| 10/10 [00:00<00:00, 2905.25it/s]
100%|██████████| 15/15 [00:01<00:00, 11.24it/s]
100%|██████████| 10/10 [00:00<00:00, 3036.05it/s]
100%|██████████| 15/15 [00:01<00:00, 12.17it/s]
100%|██████████| 10/10 [00:00<00:00, 2589.88it/s]
100%|██████████| 15/15 [00:01<00:00, 11.26it/s]
100%|██████████| 11/11 [00:00<00:00, 2880.52it/s]
100%|██████████| 15/15 [00:01<00:00, 11.46it/s]
100%|██████████| 10/10 [00:00<00:00, 2863.01it/s]
[I 2023-07-08 22:16:45,319] Trial 12 finished with value: -0.09465144779514534 and parameters: {'number_of_factors': 200, 'alpha_weight': 0.9949733700500574, 'regularization': 0.18761873644618854}. Best is trial 11 with value: -0.09690212931297347.

Fold : 5
         Average NDCG : -0.09465144779514534

100%|██████████| 15/15 [00:01<00:00, 11.05it/s]
100%|██████████| 10/10 [00:00<00:00, 3101.38it/s]
100%|██████████| 15/15 [00:01<00:00, 11.88it/s]
100%|██████████| 10/10 [00:00<00:00, 2841.28it/s]
100%|██████████| 15/15 [00:01<00:00, 12.22it/s]
100%|██████████| 10/10 [00:00<00:00, 2903.24it/s]
100%|██████████| 15/15 [00:01<00:00, 11.69it/s]
100%|██████████| 11/11 [00:00<00:00, 3156.63it/s]
100%|██████████| 15/15 [00:01<00:00, 11.85it/s]
100%|██████████| 10/10 [00:00<00:00, 3108.04it/s]
[I 2023-07-08 22:16:51,990] Trial 13 finished with value: -0.09352982884050517 and parameters: {'number_of_factors': 200, 'alpha_weight': 0.48268384487043337, 'regularization': 0.19062990247395428}. Best is trial 11 with value: -0.09690212931297347.

Fold : 5
         Average NDCG : -0.09352982884050517

100%|██████████| 15/15 [00:01<00:00, 11.86it/s]
100%|██████████| 10/10 [00:00<00:00, 2924.29it/s]
100%|██████████| 15/15 [00:01<00:00, 11.30it/s]
100%|██████████| 10/10 [00:00<00:00, 2997.64it/s]
100%|██████████| 15/15 [00:01<00:00,  9.80it/s]
100%|██████████| 10/10 [00:00<00:00, 2711.43it/s]
100%|██████████| 15/15 [00:01<00:00, 11.02it/s]
100%|██████████| 11/11 [00:00<00:00, 3067.23it/s]
100%|██████████| 15/15 [00:01<00:00,  9.73it/s]
100%|██████████| 10/10 [00:00<00:00, 2474.08it/s]
[I 2023-07-08 22:16:59,297] Trial 14 finished with value: -0.08996627203693174 and parameters: {'number_of_factors': 200, 'alpha_weight': 0.3924738465726441, 'regularization': 0.12811974516986482}. Best is trial 11 with value: -0.09690212931297347.

Fold : 5
         Average NDCG : -0.08996627203693174

100%|██████████| 15/15 [00:01<00:00, 10.39it/s]
100%|██████████| 10/10 [00:00<00:00, 2413.57it/s]
100%|██████████| 15/15 [00:01<00:00, 10.80it/s]
100%|██████████| 10/10 [00:00<00:00, 1887.71it/s]
100%|██████████| 15/15 [00:01<00:00,  8.20it/s]
100%|██████████| 10/10 [00:00<00:00, 3003.66it/s]
100%|██████████| 15/15 [00:01<00:00, 11.33it/s]
100%|██████████| 11/11 [00:00<00:00, 3103.76it/s]
100%|██████████| 15/15 [00:01<00:00, 10.54it/s]
100%|██████████| 10/10 [00:00<00:00, 2396.75it/s]
[I 2023-07-08 22:17:07,007] Trial 15 finished with value: -0.09538053356242407 and parameters: {'number_of_factors': 200, 'alpha_weight': 0.9927791783266605, 'regularization': 0.11078506368941703}. Best is trial 11 with value: -0.09690212931297347.

Fold : 5
         Average NDCG : -0.09538053356242407

100%|██████████| 15/15 [00:02<00:00,  6.31it/s]
100%|██████████| 10/10 [00:00<00:00, 1508.31it/s]
100%|██████████| 15/15 [00:02<00:00,  6.27it/s]
100%|██████████| 10/10 [00:00<00:00, 1783.90it/s]
100%|██████████| 15/15 [00:02<00:00,  6.78it/s]
100%|██████████| 10/10 [00:00<00:00, 1372.12it/s]
100%|██████████| 15/15 [00:02<00:00,  6.97it/s]
100%|██████████| 11/11 [00:00<00:00, 1737.88it/s]
100%|██████████| 15/15 [00:02<00:00,  7.03it/s]
100%|██████████| 10/10 [00:00<00:00, 1902.78it/s]
[I 2023-07-08 22:17:19,040] Trial 16 finished with value: -0.087929581281185 and parameters: {'number_of_factors': 400, 'alpha_weight': 0.4175585868852083, 'regularization': 0.09979118936096787}. Best is trial 11 with value: -0.09690212931297347.

Fold : 5
         Average NDCG : -0.087929581281185

100%|██████████| 15/15 [00:01<00:00, 10.35it/s]
100%|██████████| 10/10 [00:00<00:00, 3017.48it/s]
100%|██████████| 15/15 [00:01<00:00,  9.61it/s]
100%|██████████| 10/10 [00:00<00:00, 2751.45it/s]
100%|██████████| 15/15 [00:01<00:00,  9.73it/s]
100%|██████████| 10/10 [00:00<00:00, 2290.47it/s]
100%|██████████| 15/15 [00:01<00:00, 10.41it/s]
100%|██████████| 11/11 [00:00<00:00, 2838.70it/s]
100%|██████████| 15/15 [00:01<00:00, 11.29it/s]
100%|██████████| 10/10 [00:00<00:00, 2901.23it/s]
[I 2023-07-08 22:17:26,638] Trial 17 finished with value: -0.09048102102522383 and parameters: {'number_of_factors': 200, 'alpha_weight': 0.2724929653812518, 'regularization': 0.11299179328432106}. Best is trial 11 with value: -0.09690212931297347.

Fold : 5
         Average NDCG : -0.09048102102522383

100%|██████████| 15/15 [00:02<00:00,  6.96it/s]
100%|██████████| 10/10 [00:00<00:00, 1575.98it/s]
100%|██████████| 15/15 [00:02<00:00,  6.93it/s]
100%|██████████| 10/10 [00:00<00:00, 1500.00it/s]
100%|██████████| 15/15 [00:02<00:00,  7.06it/s]
100%|██████████| 10/10 [00:00<00:00, 1895.05it/s]
100%|██████████| 15/15 [00:02<00:00,  7.42it/s]
100%|██████████| 11/11 [00:00<00:00, 2055.48it/s]
100%|██████████| 15/15 [00:02<00:00,  6.76it/s]
100%|██████████| 10/10 [00:00<00:00, 1067.12it/s]
[I 2023-07-08 22:17:38,026] Trial 18 finished with value: -0.08989453693441084 and parameters: {'number_of_factors': 400, 'alpha_weight': 0.6272467505708078, 'regularization': 0.13843932266017786}. Best is trial 11 with value: -0.09690212931297347.

Fold : 5
         Average NDCG : -0.08989453693441084

100%|██████████| 15/15 [00:01<00:00, 10.23it/s]
100%|██████████| 10/10 [00:00<00:00, 4345.53it/s]
100%|██████████| 15/15 [00:01<00:00, 13.97it/s]
100%|██████████| 10/10 [00:00<00:00, 4607.61it/s]
100%|██████████| 15/15 [00:01<00:00, 12.69it/s]
100%|██████████| 10/10 [00:00<00:00, 2906.05it/s]
100%|██████████| 15/15 [00:01<00:00, 14.25it/s]
100%|██████████| 11/11 [00:00<00:00, 4027.35it/s]
100%|██████████| 15/15 [00:01<00:00, 11.13it/s]
100%|██████████| 10/10 [00:00<00:00, 4222.60it/s]
[I 2023-07-08 22:17:44,336] Trial 19 finished with value: -0.08746216174181072 and parameters: {'number_of_factors': 100, 'alpha_weight': 0.9924386479049389, 'regularization': 0.08236117460876916}. Best is trial 11 with value: -0.09690212931297347.

Fold : 5
         Average NDCG : -0.08746216174181072

100%|██████████| 15/15 [00:01<00:00,  9.07it/s]
100%|██████████| 10/10 [00:00<00:00, 2461.45it/s]
100%|██████████| 15/15 [00:01<00:00, 10.00it/s]
100%|██████████| 10/10 [00:00<00:00, 2595.65it/s]
100%|██████████| 15/15 [00:01<00:00,  9.22it/s]
100%|██████████| 10/10 [00:00<00:00, 2857.16it/s]
100%|██████████| 15/15 [00:01<00:00, 11.68it/s]
100%|██████████| 11/11 [00:00<00:00, 3055.25it/s]
100%|██████████| 15/15 [00:01<00:00, 11.21it/s]
100%|██████████| 10/10 [00:00<00:00, 2988.89it/s]
[I 2023-07-08 22:17:52,016] Trial 20 finished with value: -0.08903577551757128 and parameters: {'number_of_factors': 200, 'alpha_weight': 0.1430952501092991, 'regularization': 0.14257053863134664}. Best is trial 11 with value: -0.09690212931297347.

Fold : 5
         Average NDCG : -0.08903577551757128

100%|██████████| 15/15 [00:01<00:00, 10.31it/s]
100%|██████████| 10/10 [00:00<00:00, 2912.71it/s]
100%|██████████| 15/15 [00:01<00:00, 10.92it/s]
100%|██████████| 10/10 [00:00<00:00, 2752.35it/s]
100%|██████████| 15/15 [00:01<00:00,  9.89it/s]
100%|██████████| 10/10 [00:00<00:00, 2178.63it/s]
100%|██████████| 15/15 [00:01<00:00,  9.22it/s]
100%|██████████| 11/11 [00:00<00:00, 3004.32it/s]
100%|██████████| 15/15 [00:01<00:00, 10.05it/s]
100%|██████████| 10/10 [00:00<00:00, 2795.08it/s]
[I 2023-07-08 22:17:59,767] Trial 21 finished with value: -0.09474066237828602 and parameters: {'number_of_factors': 200, 'alpha_weight': 0.5688318861395132, 'regularization': 0.19003381627139984}. Best is trial 11 with value: -0.09690212931297347.

Fold : 5
         Average NDCG : -0.09474066237828602

100%|██████████| 15/15 [00:01<00:00,  9.97it/s]
100%|██████████| 10/10 [00:00<00:00, 2550.81it/s]
100%|██████████| 15/15 [00:01<00:00,  9.28it/s]
100%|██████████| 10/10 [00:00<00:00, 2986.55it/s]
100%|██████████| 15/15 [00:01<00:00,  9.73it/s]
100%|██████████| 10/10 [00:00<00:00, 2923.88it/s]
100%|██████████| 15/15 [00:01<00:00, 10.63it/s]
100%|██████████| 11/11 [00:00<00:00, 2612.53it/s]
100%|██████████| 15/15 [00:01<00:00, 10.45it/s]
100%|██████████| 10/10 [00:00<00:00, 2455.54it/s]
[I 2023-07-08 22:18:07,557] Trial 22 finished with value: -0.09870567860339219 and parameters: {'number_of_factors': 200, 'alpha_weight': 0.6034800736843645, 'regularization': 0.1560390438934994}. Best is trial 22 with value: -0.09870567860339219.

Fold : 5
         Average NDCG : -0.09870567860339219

100%|██████████| 15/15 [00:01<00:00, 11.98it/s]
100%|██████████| 10/10 [00:00<00:00, 4072.93it/s]
100%|██████████| 15/15 [00:01<00:00, 10.67it/s]
100%|██████████| 10/10 [00:00<00:00, 1513.97it/s]
100%|██████████| 15/15 [00:01<00:00, 11.13it/s]
100%|██████████| 10/10 [00:00<00:00, 3701.29it/s]
100%|██████████| 15/15 [00:01<00:00, 10.53it/s]
100%|██████████| 11/11 [00:00<00:00, 4329.30it/s]
100%|██████████| 15/15 [00:01<00:00, 11.24it/s]
100%|██████████| 10/10 [00:00<00:00, 3076.13it/s]
[I 2023-07-08 22:18:14,506] Trial 23 finished with value: -0.09506181919311366 and parameters: {'number_of_factors': 100, 'alpha_weight': 0.35169021009875057, 'regularization': 0.14537759982063894}. Best is trial 22 with value: -0.09870567860339219.

Fold : 5
         Average NDCG : -0.09506181919311366

100%|██████████| 15/15 [00:01<00:00, 10.13it/s]
100%|██████████| 10/10 [00:00<00:00, 2653.45it/s]
100%|██████████| 15/15 [00:01<00:00, 10.80it/s]
100%|██████████| 10/10 [00:00<00:00, 2922.45it/s]
100%|██████████| 15/15 [00:01<00:00, 11.49it/s]
100%|██████████| 10/10 [00:00<00:00, 2758.87it/s]
100%|██████████| 15/15 [00:01<00:00, 12.20it/s]
100%|██████████| 11/11 [00:00<00:00, 3102.09it/s]
100%|██████████| 15/15 [00:01<00:00, 11.86it/s]
100%|██████████| 10/10 [00:00<00:00, 2760.86it/s]
[I 2023-07-08 22:18:21,447] Trial 24 finished with value: -0.0926168486786736 and parameters: {'number_of_factors': 200, 'alpha_weight': 0.6299834159017204, 'regularization': 0.09942817505118537}. Best is trial 22 with value: -0.09870567860339219.

Fold : 5
         Average NDCG : -0.0926168486786736

100%|██████████| 15/15 [00:01<00:00, 10.76it/s]
100%|██████████| 10/10 [00:00<00:00, 2182.49it/s]
100%|██████████| 15/15 [00:01<00:00, 11.28it/s]
100%|██████████| 10/10 [00:00<00:00, 2429.23it/s]
100%|██████████| 15/15 [00:01<00:00, 11.10it/s]
100%|██████████| 10/10 [00:00<00:00, 2199.54it/s]
100%|██████████| 15/15 [00:01<00:00,  9.20it/s]
100%|██████████| 11/11 [00:00<00:00, 2126.83it/s]
100%|██████████| 15/15 [00:01<00:00, 10.59it/s]
100%|██████████| 10/10 [00:00<00:00, 2401.82it/s]
[I 2023-07-08 22:18:29,180] Trial 25 finished with value: -0.09367278705081178 and parameters: {'number_of_factors': 300, 'alpha_weight': 0.6331632358439946, 'regularization': 0.15631040673659985}. Best is trial 22 with value: -0.09870567860339219.

Fold : 5
         Average NDCG : -0.09367278705081178

100%|██████████| 15/15 [00:01<00:00, 11.26it/s]
100%|██████████| 10/10 [00:00<00:00, 2926.12it/s]
100%|██████████| 15/15 [00:01<00:00, 11.71it/s]
100%|██████████| 10/10 [00:00<00:00, 2869.67it/s]
100%|██████████| 15/15 [00:01<00:00, 10.57it/s]
100%|██████████| 10/10 [00:00<00:00, 2748.74it/s]
100%|██████████| 15/15 [00:01<00:00, 10.78it/s]
100%|██████████| 11/11 [00:00<00:00, 1916.16it/s]
100%|██████████| 15/15 [00:01<00:00,  9.12it/s]
100%|██████████| 10/10 [00:00<00:00, 3068.48it/s]
[I 2023-07-08 22:18:36,534] Trial 26 finished with value: -0.09727078757620651 and parameters: {'number_of_factors': 200, 'alpha_weight': 0.43273846983176706, 'regularization': 0.11292134636068629}. Best is trial 22 with value: -0.09870567860339219.

Fold : 5
         Average NDCG : -0.09727078757620651

100%|██████████| 15/15 [00:01<00:00, 12.07it/s]
100%|██████████| 10/10 [00:00<00:00, 4221.32it/s]
100%|██████████| 15/15 [00:01<00:00, 12.76it/s]
100%|██████████| 10/10 [00:00<00:00, 2868.88it/s]
100%|██████████| 15/15 [00:01<00:00, 12.08it/s]
100%|██████████| 10/10 [00:00<00:00, 4023.70it/s]
100%|██████████| 15/15 [00:01<00:00, 12.68it/s]
100%|██████████| 11/11 [00:00<00:00, 4244.47it/s]
100%|██████████| 15/15 [00:01<00:00, 11.88it/s]
100%|██████████| 10/10 [00:00<00:00, 4006.40it/s]
[I 2023-07-08 22:18:42,815] Trial 27 finished with value: -0.09354125222137158 and parameters: {'number_of_factors': 100, 'alpha_weight': 0.3767929721296307, 'regularization': 0.15608920884773894}. Best is trial 22 with value: -0.09870567860339219.

Fold : 5
         Average NDCG : -0.09354125222137158

100%|██████████| 15/15 [00:01<00:00, 10.01it/s]
100%|██████████| 10/10 [00:00<00:00, 2388.28it/s]
100%|██████████| 15/15 [00:01<00:00, 10.42it/s]
100%|██████████| 10/10 [00:00<00:00, 2268.66it/s]
100%|██████████| 15/15 [00:01<00:00, 10.76it/s]
100%|██████████| 10/10 [00:00<00:00, 1847.96it/s]
100%|██████████| 15/15 [00:01<00:00,  8.55it/s]
100%|██████████| 11/11 [00:00<00:00, 2105.09it/s]
100%|██████████| 15/15 [00:01<00:00, 10.36it/s]
100%|██████████| 10/10 [00:00<00:00, 1761.42it/s]
[I 2023-07-08 22:18:51,004] Trial 28 finished with value: -0.0895900737977269 and parameters: {'number_of_factors': 300, 'alpha_weight': 0.30193984557493403, 'regularization': 0.08102578110877945}. Best is trial 22 with value: -0.09870567860339219.

Fold : 5
         Average NDCG : -0.0895900737977269

100%|██████████| 15/15 [00:01<00:00, 10.56it/s]
100%|██████████| 10/10 [00:00<00:00, 2044.51it/s]
100%|██████████| 15/15 [00:01<00:00,  9.93it/s]
100%|██████████| 10/10 [00:00<00:00, 2213.47it/s]
100%|██████████| 15/15 [00:01<00:00,  9.18it/s]
100%|██████████| 10/10 [00:00<00:00, 1929.13it/s]
100%|██████████| 15/15 [00:01<00:00,  9.11it/s]
100%|██████████| 11/11 [00:00<00:00, 2260.75it/s]
100%|██████████| 15/15 [00:01<00:00,  7.80it/s]
100%|██████████| 10/10 [00:00<00:00, 2330.30it/s]
[I 2023-07-08 22:18:59,789] Trial 29 finished with value: -0.0901520471764328 and parameters: {'number_of_factors': 300, 'alpha_weight': 0.2125624818674737, 'regularization': 0.044047361902209446}. Best is trial 22 with value: -0.09870567860339219.

Fold : 5
         Average NDCG : -0.0901520471764328

100%|██████████| 15/15 [00:01<00:00, 11.23it/s]
100%|██████████| 10/10 [00:00<00:00, 2744.42it/s]
100%|██████████| 15/15 [00:01<00:00, 11.52it/s]
100%|██████████| 10/10 [00:00<00:00, 2425.72it/s]
100%|██████████| 15/15 [00:01<00:00, 11.55it/s]
100%|██████████| 10/10 [00:00<00:00, 2970.26it/s]
100%|██████████| 15/15 [00:01<00:00, 11.39it/s]
100%|██████████| 11/11 [00:00<00:00, 2384.11it/s]
100%|██████████| 15/15 [00:01<00:00, 11.44it/s]
100%|██████████| 10/10 [00:00<00:00, 2829.59it/s]
[I 2023-07-08 22:19:06,641] Trial 30 finished with value: -0.0930697063007714 and parameters: {'number_of_factors': 200, 'alpha_weight': 0.551205685831011, 'regularization': 0.11515682715473984}. Best is trial 22 with value: -0.09870567860339219.

Fold : 5
         Average NDCG : -0.0930697063007714

100%|██████████| 15/15 [00:01<00:00, 10.53it/s]
100%|██████████| 10/10 [00:00<00:00, 2752.53it/s]
100%|██████████| 15/15 [00:01<00:00,  9.83it/s]
100%|██████████| 10/10 [00:00<00:00, 2879.71it/s]
100%|██████████| 15/15 [00:01<00:00, 10.55it/s]
100%|██████████| 10/10 [00:00<00:00, 2794.15it/s]
100%|██████████| 15/15 [00:01<00:00, 11.10it/s]
100%|██████████| 11/11 [00:00<00:00, 2964.93it/s]
100%|██████████| 15/15 [00:01<00:00, 11.48it/s]
100%|██████████| 10/10 [00:00<00:00, 2555.17it/s]
[I 2023-07-08 22:19:13,932] Trial 31 finished with value: -0.09567360134316369 and parameters: {'number_of_factors': 200, 'alpha_weight': 0.7492988499658586, 'regularization': 0.11558326566199982}. Best is trial 22 with value: -0.09870567860339219.

Fold : 5
         Average NDCG : -0.09567360134316369

100%|██████████| 15/15 [00:01<00:00, 11.32it/s]
100%|██████████| 10/10 [00:00<00:00, 2678.53it/s]
100%|██████████| 15/15 [00:01<00:00, 11.41it/s]
100%|██████████| 10/10 [00:00<00:00, 2994.01it/s]
100%|██████████| 15/15 [00:01<00:00, 10.54it/s]
100%|██████████| 10/10 [00:00<00:00, 2664.07it/s]
100%|██████████| 15/15 [00:01<00:00, 12.12it/s]
100%|██████████| 11/11 [00:00<00:00, 2955.25it/s]
100%|██████████| 15/15 [00:01<00:00, 11.42it/s]
100%|██████████| 10/10 [00:00<00:00, 3032.76it/s]
[I 2023-07-08 22:19:20,819] Trial 32 finished with value: -0.09450672707089425 and parameters: {'number_of_factors': 200, 'alpha_weight': 0.4833931059396151, 'regularization': 0.15985856431890724}. Best is trial 22 with value: -0.09870567860339219.

Fold : 5
         Average NDCG : -0.09450672707089425

100%|██████████| 15/15 [00:01<00:00, 13.69it/s]
100%|██████████| 10/10 [00:00<00:00, 2863.98it/s]
100%|██████████| 15/15 [00:01<00:00, 13.58it/s]
100%|██████████| 10/10 [00:00<00:00, 3765.76it/s]
100%|██████████| 15/15 [00:01<00:00, 13.79it/s]
100%|██████████| 10/10 [00:00<00:00, 4419.24it/s]
100%|██████████| 15/15 [00:01<00:00, 13.52it/s]
100%|██████████| 11/11 [00:00<00:00, 4631.80it/s]
100%|██████████| 15/15 [00:01<00:00, 12.88it/s]
100%|██████████| 10/10 [00:00<00:00, 4635.61it/s]
[I 2023-07-08 22:19:26,544] Trial 33 finished with value: -0.0952942734195358 and parameters: {'number_of_factors': 100, 'alpha_weight': 0.7673609328334162, 'regularization': 0.1282280918089423}. Best is trial 22 with value: -0.09870567860339219.

Fold : 5
         Average NDCG : -0.0952942734195358

100%|██████████| 15/15 [00:01<00:00, 11.40it/s]
100%|██████████| 10/10 [00:00<00:00, 1903.65it/s]
100%|██████████| 15/15 [00:01<00:00, 11.47it/s]
100%|██████████| 10/10 [00:00<00:00, 2427.96it/s]
100%|██████████| 15/15 [00:01<00:00, 11.40it/s]
100%|██████████| 10/10 [00:00<00:00, 2014.65it/s]
100%|██████████| 15/15 [00:01<00:00, 11.41it/s]
100%|██████████| 11/11 [00:00<00:00, 2588.06it/s]
100%|██████████| 15/15 [00:01<00:00, 11.43it/s]
100%|██████████| 10/10 [00:00<00:00, 2259.50it/s]
[I 2023-07-08 22:19:33,747] Trial 34 finished with value: -0.09432253157593298 and parameters: {'number_of_factors': 300, 'alpha_weight': 0.7658379613337651, 'regularization': 0.197695253652723}. Best is trial 22 with value: -0.09870567860339219.

Fold : 5
         Average NDCG : -0.09432253157593298

100%|██████████| 15/15 [00:01<00:00, 12.11it/s]
100%|██████████| 10/10 [00:00<00:00, 2988.03it/s]
100%|██████████| 15/15 [00:01<00:00, 11.92it/s]
100%|██████████| 10/10 [00:00<00:00, 3202.49it/s]
100%|██████████| 15/15 [00:01<00:00, 11.52it/s]
100%|██████████| 10/10 [00:00<00:00, 2299.00it/s]
100%|██████████| 15/15 [00:01<00:00, 10.38it/s]
100%|██████████| 11/11 [00:00<00:00, 2723.73it/s]
100%|██████████| 15/15 [00:01<00:00, 10.08it/s]
100%|██████████| 10/10 [00:00<00:00, 2632.30it/s]
[I 2023-07-08 22:19:40,750] Trial 35 finished with value: -0.09259327622139135 and parameters: {'number_of_factors': 200, 'alpha_weight': 0.41809396837746904, 'regularization': 0.09240545074370453}. Best is trial 22 with value: -0.09870567860339219.

Fold : 5
         Average NDCG : -0.09259327622139135

100%|██████████| 15/15 [00:01<00:00, 10.47it/s]
100%|██████████| 10/10 [00:00<00:00, 3640.26it/s]
100%|██████████| 15/15 [00:01<00:00, 12.68it/s]
100%|██████████| 10/10 [00:00<00:00, 3836.72it/s]
100%|██████████| 15/15 [00:01<00:00, 13.14it/s]
100%|██████████| 10/10 [00:00<00:00, 4094.40it/s]
100%|██████████| 15/15 [00:01<00:00, 13.02it/s]
100%|██████████| 11/11 [00:00<00:00, 4041.82it/s]
100%|██████████| 15/15 [00:01<00:00, 13.34it/s]
100%|██████████| 10/10 [00:00<00:00, 4569.95it/s]
[I 2023-07-08 22:19:46,965] Trial 36 finished with value: -0.09336842247769807 and parameters: {'number_of_factors': 100, 'alpha_weight': 0.7133555715667187, 'regularization': 0.12329449948492664}. Best is trial 22 with value: -0.09870567860339219.

Fold : 5
         Average NDCG : -0.09336842247769807

100%|██████████| 15/15 [00:01<00:00, 10.52it/s]
100%|██████████| 10/10 [00:00<00:00, 2436.42it/s]
100%|██████████| 15/15 [00:01<00:00, 10.70it/s]
100%|██████████| 10/10 [00:00<00:00, 2256.82it/s]
100%|██████████| 15/15 [00:01<00:00, 10.48it/s]
100%|██████████| 10/10 [00:00<00:00, 2310.53it/s]
100%|██████████| 15/15 [00:01<00:00,  9.11it/s]
100%|██████████| 11/11 [00:00<00:00, 2313.46it/s]
100%|██████████| 15/15 [00:01<00:00, 10.44it/s]
100%|██████████| 10/10 [00:00<00:00, 2019.02it/s]
[I 2023-07-08 22:19:54,925] Trial 37 finished with value: -0.0850092756298371 and parameters: {'number_of_factors': 300, 'alpha_weight': 0.47811872044853165, 'regularization': 0.07047377202141762}. Best is trial 22 with value: -0.09870567860339219.

Fold : 5
         Average NDCG : -0.0850092756298371

100%|██████████| 15/15 [00:01<00:00, 10.89it/s]
100%|██████████| 10/10 [00:00<00:00, 2277.04it/s]
100%|██████████| 15/15 [00:01<00:00, 11.24it/s]
100%|██████████| 10/10 [00:00<00:00, 2441.96it/s]
100%|██████████| 15/15 [00:01<00:00, 10.65it/s]
100%|██████████| 10/10 [00:00<00:00, 2142.14it/s]
100%|██████████| 15/15 [00:01<00:00, 11.25it/s]
100%|██████████| 11/11 [00:00<00:00, 2428.28it/s]
100%|██████████| 15/15 [00:01<00:00, 10.96it/s]
100%|██████████| 10/10 [00:00<00:00, 2465.06it/s]
[I 2023-07-08 22:20:02,340] Trial 38 finished with value: -0.08665716551720595 and parameters: {'number_of_factors': 300, 'alpha_weight': 0.18160328676645998, 'regularization': 0.16733758945282518}. Best is trial 22 with value: -0.09870567860339219.

Fold : 5
         Average NDCG : -0.08665716551720595

100%|██████████| 15/15 [00:01<00:00, 11.86it/s]
100%|██████████| 10/10 [00:00<00:00, 1866.79it/s]
100%|██████████| 15/15 [00:01<00:00, 12.17it/s]
100%|██████████| 10/10 [00:00<00:00, 2802.56it/s]
100%|██████████| 15/15 [00:01<00:00, 11.48it/s]
100%|██████████| 10/10 [00:00<00:00, 2940.89it/s]
100%|██████████| 15/15 [00:01<00:00, 12.00it/s]
100%|██████████| 11/11 [00:00<00:00, 2993.02it/s]
100%|██████████| 15/15 [00:01<00:00, 11.88it/s]
100%|██████████| 10/10 [00:00<00:00, 3026.63it/s]
[I 2023-07-08 22:20:08,941] Trial 39 finished with value: -0.0912782002158652 and parameters: {'number_of_factors': 200, 'alpha_weight': 0.3212160044380516, 'regularization': 0.10426249978484893}. Best is trial 22 with value: -0.09870567860339219.

Fold : 5
         Average NDCG : -0.0912782002158652

100%|██████████| 15/15 [00:01<00:00, 13.19it/s]
100%|██████████| 10/10 [00:00<00:00, 4464.88it/s]
100%|██████████| 15/15 [00:01<00:00, 13.65it/s]
100%|██████████| 10/10 [00:00<00:00, 3980.93it/s]
100%|██████████| 15/15 [00:01<00:00, 13.49it/s]
100%|██████████| 10/10 [00:00<00:00, 3095.43it/s]
100%|██████████| 15/15 [00:01<00:00, 13.38it/s]
100%|██████████| 11/11 [00:00<00:00, 3914.59it/s]
100%|██████████| 15/15 [00:01<00:00, 12.49it/s]
100%|██████████| 10/10 [00:00<00:00, 2944.20it/s]
[I 2023-07-08 22:20:14,793] Trial 40 finished with value: -0.08988407337343814 and parameters: {'number_of_factors': 100, 'alpha_weight': 0.7891197959357084, 'regularization': 0.13094665388418023}. Best is trial 22 with value: -0.09870567860339219.

Fold : 5
         Average NDCG : -0.08988407337343814

100%|██████████| 15/15 [00:01<00:00, 11.97it/s]
100%|██████████| 10/10 [00:00<00:00, 2818.56it/s]
100%|██████████| 15/15 [00:01<00:00, 12.18it/s]
100%|██████████| 10/10 [00:00<00:00, 2957.48it/s]
100%|██████████| 15/15 [00:01<00:00, 12.06it/s]
100%|██████████| 10/10 [00:00<00:00, 2939.66it/s]
100%|██████████| 15/15 [00:01<00:00, 12.04it/s]
100%|██████████| 11/11 [00:00<00:00, 2956.01it/s]
100%|██████████| 15/15 [00:01<00:00, 12.01it/s]
100%|██████████| 10/10 [00:00<00:00, 2909.28it/s]
[I 2023-07-08 22:20:21,283] Trial 41 finished with value: -0.09774002973645189 and parameters: {'number_of_factors': 200, 'alpha_weight': 0.9903374378402794, 'regularization': 0.11427688929576274}. Best is trial 22 with value: -0.09870567860339219.

Fold : 5
         Average NDCG : -0.09774002973645189

100%|██████████| 15/15 [00:01<00:00, 11.83it/s]
100%|██████████| 10/10 [00:00<00:00, 2871.04it/s]
100%|██████████| 15/15 [00:01<00:00, 10.25it/s]
100%|██████████| 10/10 [00:00<00:00, 2922.66it/s]
100%|██████████| 15/15 [00:01<00:00, 11.15it/s]
100%|██████████| 10/10 [00:00<00:00, 3035.83it/s]
100%|██████████| 15/15 [00:01<00:00, 11.23it/s]
100%|██████████| 11/11 [00:00<00:00, 2656.92it/s]
100%|██████████| 15/15 [00:01<00:00, 11.27it/s]
100%|██████████| 10/10 [00:00<00:00, 961.95it/s]
[I 2023-07-08 22:20:28,312] Trial 42 finished with value: -0.0990581953048089 and parameters: {'number_of_factors': 200, 'alpha_weight': 0.7949060835339161, 'regularization': 0.16548635928855224}. Best is trial 42 with value: -0.0990581953048089.

Fold : 5
         Average NDCG : -0.0990581953048089

100%|██████████| 15/15 [00:01<00:00, 11.45it/s]
100%|██████████| 10/10 [00:00<00:00, 2404.99it/s]
100%|██████████| 15/15 [00:01<00:00, 11.59it/s]
100%|██████████| 10/10 [00:00<00:00, 2742.45it/s]
100%|██████████| 15/15 [00:01<00:00, 11.57it/s]
100%|██████████| 10/10 [00:00<00:00, 2673.57it/s]
100%|██████████| 15/15 [00:01<00:00, 11.47it/s]
100%|██████████| 11/11 [00:00<00:00, 3370.64it/s]
100%|██████████| 15/15 [00:01<00:00, 12.01it/s]
100%|██████████| 10/10 [00:00<00:00, 2471.89it/s]
[I 2023-07-08 22:20:35,036] Trial 43 finished with value: -0.09915199294632102 and parameters: {'number_of_factors': 200, 'alpha_weight': 0.528034955867602, 'regularization': 0.16395015816267147}. Best is trial 43 with value: -0.09915199294632102.

Fold : 5
         Average NDCG : -0.09915199294632102

100%|██████████| 15/15 [00:01<00:00, 12.18it/s]
100%|██████████| 10/10 [00:00<00:00, 2597.57it/s]
100%|██████████| 15/15 [00:01<00:00, 11.95it/s]
100%|██████████| 10/10 [00:00<00:00, 2954.15it/s]
100%|██████████| 15/15 [00:01<00:00, 12.01it/s]
100%|██████████| 10/10 [00:00<00:00, 2766.51it/s]
100%|██████████| 15/15 [00:01<00:00, 11.94it/s]
100%|██████████| 11/11 [00:00<00:00, 3112.76it/s]
100%|██████████| 15/15 [00:01<00:00, 11.89it/s]
100%|██████████| 10/10 [00:00<00:00, 2933.49it/s]
[I 2023-07-08 22:20:41,566] Trial 44 finished with value: -0.0964008457548318 and parameters: {'number_of_factors': 200, 'alpha_weight': 0.5321612315815271, 'regularization': 0.15074787177865842}. Best is trial 43 with value: -0.09915199294632102.

Fold : 5
         Average NDCG : -0.0964008457548318

100%|██████████| 15/15 [00:01<00:00, 13.62it/s]
100%|██████████| 10/10 [00:00<00:00, 4061.89it/s]
100%|██████████| 15/15 [00:01<00:00, 13.46it/s]
100%|██████████| 10/10 [00:00<00:00, 4102.01it/s]
100%|██████████| 15/15 [00:01<00:00, 13.11it/s]
100%|██████████| 10/10 [00:00<00:00, 3799.53it/s]
100%|██████████| 15/15 [00:01<00:00, 12.78it/s]
100%|██████████| 11/11 [00:00<00:00, 4603.15it/s]
100%|██████████| 15/15 [00:01<00:00, 13.40it/s]
100%|██████████| 10/10 [00:00<00:00, 4075.31it/s]
[I 2023-07-08 22:20:47,402] Trial 45 finished with value: -0.09509879214363454 and parameters: {'number_of_factors': 100, 'alpha_weight': 0.26906309277695495, 'regularization': 0.09282339304614437}. Best is trial 43 with value: -0.09915199294632102.

Fold : 5
         Average NDCG : -0.09509879214363454

100%|██████████| 15/15 [00:01<00:00, 11.42it/s]
100%|██████████| 10/10 [00:00<00:00, 2682.47it/s]
100%|██████████| 15/15 [00:01<00:00, 10.62it/s]
100%|██████████| 10/10 [00:00<00:00, 2926.94it/s]
100%|██████████| 15/15 [00:01<00:00, 11.79it/s]
100%|██████████| 10/10 [00:00<00:00, 2733.34it/s]
100%|██████████| 15/15 [00:01<00:00, 12.14it/s]
100%|██████████| 11/11 [00:00<00:00, 3083.84it/s]
100%|██████████| 15/15 [00:01<00:00, 11.70it/s]
100%|██████████| 10/10 [00:00<00:00, 2856.77it/s]
[I 2023-07-08 22:20:54,199] Trial 46 finished with value: -0.09135644651555053 and parameters: {'number_of_factors': 200, 'alpha_weight': 0.47274921507177387, 'regularization': 0.16662056617606813}. Best is trial 43 with value: -0.09915199294632102.

Fold : 5
         Average NDCG : -0.09135644651555053

100%|██████████| 15/15 [00:02<00:00,  6.23it/s]
100%|██████████| 10/10 [00:00<00:00, 1654.10it/s]
100%|██████████| 15/15 [00:02<00:00,  6.33it/s]
100%|██████████| 10/10 [00:00<00:00, 1617.17it/s]
100%|██████████| 15/15 [00:02<00:00,  6.29it/s]
100%|██████████| 10/10 [00:00<00:00, 1620.05it/s]
100%|██████████| 15/15 [00:02<00:00,  6.33it/s]
100%|██████████| 11/11 [00:00<00:00, 1727.08it/s]
100%|██████████| 15/15 [00:02<00:00,  6.27it/s]
100%|██████████| 10/10 [00:00<00:00, 1440.60it/s]
[I 2023-07-08 22:21:07,524] Trial 47 finished with value: -0.08539356471074619 and parameters: {'number_of_factors': 500, 'alpha_weight': 0.8902928956665476, 'regularization': 0.13357083284907326}. Best is trial 43 with value: -0.09915199294632102.

Fold : 5
         Average NDCG : -0.08539356471074619

100%|██████████| 15/15 [00:01<00:00, 11.47it/s]
100%|██████████| 10/10 [00:00<00:00, 2392.78it/s]
100%|██████████| 15/15 [00:01<00:00, 11.56it/s]
100%|██████████| 10/10 [00:00<00:00, 2495.57it/s]
100%|██████████| 15/15 [00:01<00:00, 11.21it/s]
100%|██████████| 10/10 [00:00<00:00, 2433.46it/s]
100%|██████████| 15/15 [00:01<00:00, 11.49it/s]
100%|██████████| 11/11 [00:00<00:00, 2564.75it/s]
100%|██████████| 15/15 [00:01<00:00, 11.20it/s]
100%|██████████| 10/10 [00:00<00:00, 2343.45it/s]
[I 2023-07-08 22:21:14,669] Trial 48 finished with value: -0.09187585547522606 and parameters: {'number_of_factors': 300, 'alpha_weight': 0.616502823042277, 'regularization': 0.16740323453652148}. Best is trial 43 with value: -0.09915199294632102.

Fold : 5
         Average NDCG : -0.09187585547522606

100%|██████████| 15/15 [00:01<00:00, 12.17it/s]
100%|██████████| 10/10 [00:00<00:00, 3150.30it/s]
100%|██████████| 15/15 [00:01<00:00, 11.63it/s]
100%|██████████| 10/10 [00:00<00:00, 2994.65it/s]
100%|██████████| 15/15 [00:01<00:00, 11.84it/s]
100%|██████████| 10/10 [00:00<00:00, 3048.85it/s]
100%|██████████| 15/15 [00:01<00:00, 12.21it/s]
100%|██████████| 11/11 [00:00<00:00, 3031.36it/s]
100%|██████████| 15/15 [00:01<00:00, 11.96it/s]
100%|██████████| 10/10 [00:00<00:00, 2986.12it/s]
[I 2023-07-08 22:21:21,223] Trial 49 finished with value: -0.09200196609587565 and parameters: {'number_of_factors': 200, 'alpha_weight': 0.3655720231420095, 'regularization': 0.11862123055069745}. Best is trial 43 with value: -0.09915199294632102.

Fold : 5
         Average NDCG : -0.09200196609587565

100%|██████████| 15/15 [00:01<00:00, 12.12it/s]
100%|██████████| 10/10 [00:00<00:00, 3123.78it/s]
100%|██████████| 15/15 [00:01<00:00, 12.21it/s]
100%|██████████| 10/10 [00:00<00:00, 3008.18it/s]
100%|██████████| 15/15 [00:01<00:00, 11.93it/s]
100%|██████████| 10/10 [00:00<00:00, 2628.34it/s]
100%|██████████| 15/15 [00:01<00:00, 12.24it/s]
100%|██████████| 11/11 [00:00<00:00, 3209.33it/s]
100%|██████████| 15/15 [00:01<00:00, 12.02it/s]
100%|██████████| 10/10 [00:00<00:00, 2510.66it/s]
[I 2023-07-08 22:21:27,687] Trial 50 finished with value: -0.09295683139193006 and parameters: {'number_of_factors': 200, 'alpha_weight': 0.8521145717512553, 'regularization': 0.059703207240934315}. Best is trial 43 with value: -0.09915199294632102.

Fold : 5
         Average NDCG : -0.09295683139193006

100%|██████████| 15/15 [00:01<00:00, 11.88it/s]
100%|██████████| 10/10 [00:00<00:00, 3022.49it/s]
100%|██████████| 15/15 [00:01<00:00, 12.15it/s]
100%|██████████| 10/10 [00:00<00:00, 3122.62it/s]
100%|██████████| 15/15 [00:01<00:00, 11.85it/s]
100%|██████████| 10/10 [00:00<00:00, 2903.64it/s]
100%|██████████| 15/15 [00:01<00:00, 12.24it/s]
100%|██████████| 11/11 [00:00<00:00, 3031.96it/s]
100%|██████████| 15/15 [00:01<00:00, 12.04it/s]
100%|██████████| 10/10 [00:00<00:00, 2944.61it/s]
[I 2023-07-08 22:21:34,189] Trial 51 finished with value: -0.09246838771169405 and parameters: {'number_of_factors': 200, 'alpha_weight': 0.7257585157970912, 'regularization': 0.17996619287948326}. Best is trial 43 with value: -0.09915199294632102.

Fold : 5
         Average NDCG : -0.09246838771169405

100%|██████████| 15/15 [00:01<00:00, 12.00it/s]
100%|██████████| 10/10 [00:00<00:00, 3127.98it/s]
100%|██████████| 15/15 [00:01<00:00, 12.08it/s]
100%|██████████| 10/10 [00:00<00:00, 2993.15it/s]
100%|██████████| 15/15 [00:01<00:00, 12.05it/s]
100%|██████████| 10/10 [00:00<00:00, 3075.00it/s]
100%|██████████| 15/15 [00:01<00:00, 11.99it/s]
100%|██████████| 11/11 [00:00<00:00, 3134.12it/s]
100%|██████████| 15/15 [00:01<00:00, 11.46it/s]
100%|██████████| 10/10 [00:00<00:00, 2981.24it/s]
[I 2023-07-08 22:21:40,783] Trial 52 finished with value: -0.09183019473566603 and parameters: {'number_of_factors': 200, 'alpha_weight': 0.9925559796149338, 'regularization': 0.19966798870751568}. Best is trial 43 with value: -0.09915199294632102.

Fold : 5
         Average NDCG : -0.09183019473566603

100%|██████████| 15/15 [00:01<00:00, 11.59it/s]
100%|██████████| 10/10 [00:00<00:00, 2800.12it/s]
100%|██████████| 15/15 [00:01<00:00, 11.65it/s]
100%|██████████| 10/10 [00:00<00:00, 3182.08it/s]
100%|██████████| 15/15 [00:01<00:00, 11.77it/s]
100%|██████████| 10/10 [00:00<00:00, 2992.72it/s]
100%|██████████| 15/15 [00:01<00:00, 11.97it/s]
100%|██████████| 11/11 [00:00<00:00, 3014.13it/s]
100%|██████████| 15/15 [00:01<00:00, 10.53it/s]
100%|██████████| 10/10 [00:00<00:00, 2930.62it/s]
[I 2023-07-08 22:21:47,595] Trial 53 finished with value: -0.09369818212896515 and parameters: {'number_of_factors': 200, 'alpha_weight': 0.5527608886397913, 'regularization': 0.17104742315935453}. Best is trial 43 with value: -0.09915199294632102.

Fold : 5
         Average NDCG : -0.09369818212896515

100%|██████████| 15/15 [00:01<00:00, 10.45it/s]
100%|██████████| 10/10 [00:00<00:00, 2865.35it/s]
100%|██████████| 15/15 [00:01<00:00, 11.55it/s]
100%|██████████| 10/10 [00:00<00:00, 2924.69it/s]
100%|██████████| 15/15 [00:01<00:00, 11.90it/s]
100%|██████████| 10/10 [00:00<00:00, 3009.91it/s]
100%|██████████| 15/15 [00:01<00:00, 11.28it/s]
100%|██████████| 11/11 [00:00<00:00, 2977.95it/s]
100%|██████████| 15/15 [00:01<00:00, 11.21it/s]
100%|██████████| 10/10 [00:00<00:00, 3031.66it/s]
[I 2023-07-08 22:21:54,528] Trial 54 finished with value: -0.09313603473284161 and parameters: {'number_of_factors': 200, 'alpha_weight': 0.8376624445995066, 'regularization': 0.1428196879397408}. Best is trial 43 with value: -0.09915199294632102.

Fold : 5
         Average NDCG : -0.09313603473284161

100%|██████████| 15/15 [00:01<00:00, 11.51it/s]
100%|██████████| 10/10 [00:00<00:00, 3018.35it/s]
100%|██████████| 15/15 [00:01<00:00, 11.27it/s]
100%|██████████| 10/10 [00:00<00:00, 2432.61it/s]
100%|██████████| 15/15 [00:01<00:00, 11.66it/s]
100%|██████████| 10/10 [00:00<00:00, 3149.59it/s]
100%|██████████| 15/15 [00:01<00:00, 11.97it/s]
100%|██████████| 11/11 [00:00<00:00, 3139.02it/s]
100%|██████████| 15/15 [00:01<00:00, 12.00it/s]
100%|██████████| 10/10 [00:00<00:00, 3004.30it/s]
[I 2023-07-08 22:22:01,228] Trial 55 finished with value: -0.09342311540782205 and parameters: {'number_of_factors': 200, 'alpha_weight': 0.6845981686101387, 'regularization': 0.1390563323031433}. Best is trial 43 with value: -0.09915199294632102.

Fold : 5
         Average NDCG : -0.09342311540782205

100%|██████████| 15/15 [00:01<00:00, 13.29it/s]
100%|██████████| 10/10 [00:00<00:00, 4450.19it/s]
100%|██████████| 15/15 [00:01<00:00, 13.67it/s]
100%|██████████| 10/10 [00:00<00:00, 4081.25it/s]
100%|██████████| 15/15 [00:01<00:00, 13.85it/s]
100%|██████████| 10/10 [00:00<00:00, 4568.96it/s]
100%|██████████| 15/15 [00:01<00:00, 13.41it/s]
100%|██████████| 11/11 [00:00<00:00, 4184.41it/s]
100%|██████████| 15/15 [00:01<00:00, 13.65it/s]
100%|██████████| 10/10 [00:00<00:00, 3102.07it/s]
[I 2023-07-08 22:22:06,922] Trial 56 finished with value: -0.09372751206294029 and parameters: {'number_of_factors': 100, 'alpha_weight': 0.42566404730913243, 'regularization': 0.1841442228425916}. Best is trial 43 with value: -0.09915199294632102.

Fold : 5
         Average NDCG : -0.09372751206294029

100%|██████████| 15/15 [00:01<00:00, 11.97it/s]
100%|██████████| 10/10 [00:00<00:00, 2328.75it/s]
100%|██████████| 15/15 [00:01<00:00, 11.85it/s]
100%|██████████| 10/10 [00:00<00:00, 2962.71it/s]
100%|██████████| 15/15 [00:01<00:00, 11.92it/s]
100%|██████████| 10/10 [00:00<00:00, 3027.72it/s]
100%|██████████| 15/15 [00:01<00:00, 11.93it/s]
100%|██████████| 11/11 [00:00<00:00, 3043.96it/s]
100%|██████████| 15/15 [00:01<00:00, 11.78it/s]
100%|██████████| 10/10 [00:00<00:00, 3135.93it/s]
[I 2023-07-08 22:22:13,505] Trial 57 finished with value: -0.09595810567680149 and parameters: {'number_of_factors': 200, 'alpha_weight': 0.5980158299005257, 'regularization': 0.1508724833637858}. Best is trial 43 with value: -0.09915199294632102.

Fold : 5
         Average NDCG : -0.09595810567680149

100%|██████████| 15/15 [00:01<00:00, 11.40it/s]
100%|██████████| 10/10 [00:00<00:00, 2214.05it/s]
100%|██████████| 15/15 [00:01<00:00, 11.19it/s]
100%|██████████| 10/10 [00:00<00:00, 2463.33it/s]
100%|██████████| 15/15 [00:01<00:00, 11.13it/s]
100%|██████████| 10/10 [00:00<00:00, 2451.09it/s]
100%|██████████| 15/15 [00:01<00:00, 11.27it/s]
100%|██████████| 11/11 [00:00<00:00, 2028.64it/s]
100%|██████████| 15/15 [00:01<00:00, 11.09it/s]
100%|██████████| 10/10 [00:00<00:00, 2000.14it/s]
[I 2023-07-08 22:22:20,766] Trial 58 finished with value: -0.08746154314391764 and parameters: {'number_of_factors': 300, 'alpha_weight': 0.8500768547252476, 'regularization': 0.12291731109384897}. Best is trial 43 with value: -0.09915199294632102.

Fold : 5
         Average NDCG : -0.08746154314391764

100%|██████████| 15/15 [00:01<00:00, 12.03it/s]
100%|██████████| 10/10 [00:00<00:00, 2936.57it/s]
100%|██████████| 15/15 [00:01<00:00, 11.92it/s]
100%|██████████| 10/10 [00:00<00:00, 3030.13it/s]
100%|██████████| 15/15 [00:01<00:00, 11.23it/s]
100%|██████████| 10/10 [00:00<00:00, 2983.57it/s]
100%|██████████| 15/15 [00:01<00:00, 12.08it/s]
100%|██████████| 11/11 [00:00<00:00, 2416.33it/s]
100%|██████████| 15/15 [00:01<00:00, 12.03it/s]
100%|██████████| 10/10 [00:00<00:00, 2970.05it/s]
[I 2023-07-08 22:22:27,370] Trial 59 finished with value: -0.09474758127901678 and parameters: {'number_of_factors': 200, 'alpha_weight': 0.4841658062846433, 'regularization': 0.17374724551084128}. Best is trial 43 with value: -0.09915199294632102.

Fold : 5
         Average NDCG : -0.09474758127901678

100%|██████████| 15/15 [00:01<00:00, 12.21it/s]
100%|██████████| 10/10 [00:00<00:00, 3583.65it/s]
100%|██████████| 15/15 [00:01<00:00, 13.08it/s]
100%|██████████| 10/10 [00:00<00:00, 3902.77it/s]
100%|██████████| 15/15 [00:01<00:00, 13.51it/s]
100%|██████████| 10/10 [00:00<00:00, 3953.16it/s]
100%|██████████| 15/15 [00:01<00:00, 13.33it/s]
100%|██████████| 11/11 [00:00<00:00, 3904.32it/s]
100%|██████████| 15/15 [00:01<00:00, 12.87it/s]
100%|██████████| 10/10 [00:00<00:00, 4154.01it/s]
[I 2023-07-08 22:22:33,335] Trial 60 finished with value: -0.09685510900405177 and parameters: {'number_of_factors': 100, 'alpha_weight': 0.6317454222509504, 'regularization': 0.19865850934011384}. Best is trial 43 with value: -0.09915199294632102.

Fold : 5
         Average NDCG : -0.09685510900405177

100%|██████████| 15/15 [00:01<00:00, 13.56it/s]
100%|██████████| 10/10 [00:00<00:00, 2472.62it/s]
100%|██████████| 15/15 [00:01<00:00, 13.11it/s]
100%|██████████| 10/10 [00:00<00:00, 3952.79it/s]
100%|██████████| 15/15 [00:01<00:00, 13.15it/s]
100%|██████████| 10/10 [00:00<00:00, 4170.12it/s]
100%|██████████| 15/15 [00:01<00:00, 13.12it/s]
100%|██████████| 11/11 [00:00<00:00, 3951.81it/s]
100%|██████████| 15/15 [00:01<00:00, 12.63it/s]
100%|██████████| 10/10 [00:00<00:00, 4188.86it/s]
[I 2023-07-08 22:22:39,234] Trial 61 finished with value: -0.09408529906163432 and parameters: {'number_of_factors': 100, 'alpha_weight': 0.6690210365206569, 'regularization': 0.19707478811706133}. Best is trial 43 with value: -0.09915199294632102.

Fold : 5
         Average NDCG : -0.09408529906163432

100%|██████████| 15/15 [00:01<00:00, 13.22it/s]
100%|██████████| 10/10 [00:00<00:00, 4421.11it/s]
100%|██████████| 15/15 [00:01<00:00, 13.78it/s]
100%|██████████| 10/10 [00:00<00:00, 4145.39it/s]
100%|██████████| 15/15 [00:01<00:00, 13.22it/s]
100%|██████████| 10/10 [00:00<00:00, 4270.75it/s]
100%|██████████| 15/15 [00:01<00:00, 13.59it/s]
100%|██████████| 11/11 [00:00<00:00, 4370.72it/s]
100%|██████████| 15/15 [00:01<00:00, 13.72it/s]
100%|██████████| 10/10 [00:00<00:00, 4413.20it/s]
[I 2023-07-08 22:22:44,960] Trial 62 finished with value: -0.09471759618814025 and parameters: {'number_of_factors': 100, 'alpha_weight': 0.9167902145118959, 'regularization': 0.15665845875468404}. Best is trial 43 with value: -0.09915199294632102.

Fold : 5
         Average NDCG : -0.09471759618814025

100%|██████████| 15/15 [00:01<00:00, 13.81it/s]
100%|██████████| 10/10 [00:00<00:00, 4274.67it/s]
100%|██████████| 15/15 [00:01<00:00, 13.43it/s]
100%|██████████| 10/10 [00:00<00:00, 4242.67it/s]
100%|██████████| 15/15 [00:01<00:00, 13.67it/s]
100%|██████████| 10/10 [00:00<00:00, 3240.10it/s]
100%|██████████| 15/15 [00:01<00:00, 13.02it/s]
100%|██████████| 11/11 [00:00<00:00, 4432.45it/s]
100%|██████████| 15/15 [00:01<00:00, 12.62it/s]
100%|██████████| 10/10 [00:00<00:00, 3068.70it/s]
[I 2023-07-08 22:22:50,761] Trial 63 finished with value: -0.10012063435717589 and parameters: {'number_of_factors': 100, 'alpha_weight': 0.6585942140671041, 'regularization': 0.17824804525179394}. Best is trial 63 with value: -0.10012063435717589.

Fold : 5
         Average NDCG : -0.10012063435717589

100%|██████████| 15/15 [00:01<00:00,  7.72it/s]
100%|██████████| 10/10 [00:00<00:00, 1846.08it/s]
100%|██████████| 15/15 [00:01<00:00,  7.61it/s]
100%|██████████| 10/10 [00:00<00:00, 1726.76it/s]
100%|██████████| 15/15 [00:01<00:00,  7.50it/s]
100%|██████████| 10/10 [00:00<00:00, 1913.98it/s]
100%|██████████| 15/15 [00:02<00:00,  7.41it/s]
100%|██████████| 11/11 [00:00<00:00, 2007.63it/s]
100%|██████████| 15/15 [00:01<00:00,  7.58it/s]
100%|██████████| 10/10 [00:00<00:00, 1980.50it/s]
[I 2023-07-08 22:23:01,351] Trial 64 finished with value: -0.08920943598021767 and parameters: {'number_of_factors': 400, 'alpha_weight': 0.5463894818448973, 'regularization': 0.10873856843061142}. Best is trial 63 with value: -0.10012063435717589.

Fold : 5
         Average NDCG : -0.08920943598021767

100%|██████████| 15/15 [00:01<00:00, 11.36it/s]
100%|██████████| 10/10 [00:00<00:00, 2931.03it/s]
100%|██████████| 15/15 [00:01<00:00, 10.96it/s]
100%|██████████| 10/10 [00:00<00:00, 2554.85it/s]
100%|██████████| 15/15 [00:01<00:00, 11.73it/s]
100%|██████████| 10/10 [00:00<00:00, 2588.12it/s]
100%|██████████| 15/15 [00:01<00:00, 11.24it/s]
100%|██████████| 11/11 [00:00<00:00, 3076.44it/s]
100%|██████████| 15/15 [00:01<00:00, 11.05it/s]
100%|██████████| 10/10 [00:00<00:00, 2951.86it/s]
[I 2023-07-08 22:23:08,289] Trial 65 finished with value: -0.09697166369571351 and parameters: {'number_of_factors': 200, 'alpha_weight': 0.9850740787129381, 'regularization': 0.14050694415954298}. Best is trial 63 with value: -0.10012063435717589.

Fold : 5
         Average NDCG : -0.09697166369571351

100%|██████████| 15/15 [00:01<00:00, 11.00it/s]
100%|██████████| 10/10 [00:00<00:00, 2186.93it/s]
100%|██████████| 15/15 [00:01<00:00, 11.19it/s]
100%|██████████| 10/10 [00:00<00:00, 2421.93it/s]
100%|██████████| 15/15 [00:01<00:00, 11.21it/s]
100%|██████████| 10/10 [00:00<00:00, 3180.39it/s]
100%|██████████| 15/15 [00:01<00:00, 11.07it/s]
100%|██████████| 11/11 [00:00<00:00, 2398.99it/s]
100%|██████████| 15/15 [00:01<00:00, 10.97it/s]
100%|██████████| 10/10 [00:00<00:00, 2269.65it/s]
[I 2023-07-08 22:23:15,613] Trial 66 finished with value: -0.09030897708402638 and parameters: {'number_of_factors': 300, 'alpha_weight': 0.9902368849293732, 'regularization': 0.13543768204023782}. Best is trial 63 with value: -0.10012063435717589.

Fold : 5
         Average NDCG : -0.09030897708402638

100%|██████████| 15/15 [00:01<00:00, 12.00it/s]
100%|██████████| 10/10 [00:00<00:00, 3079.29it/s]
100%|██████████| 15/15 [00:01<00:00, 11.38it/s]
100%|██████████| 10/10 [00:00<00:00, 2918.79it/s]
100%|██████████| 15/15 [00:01<00:00, 12.09it/s]
100%|██████████| 10/10 [00:00<00:00, 3012.28it/s]
100%|██████████| 15/15 [00:01<00:00, 11.88it/s]
100%|██████████| 11/11 [00:00<00:00, 3305.68it/s]
100%|██████████| 15/15 [00:01<00:00, 12.08it/s]
100%|██████████| 10/10 [00:00<00:00, 3089.27it/s]
[I 2023-07-08 22:23:22,198] Trial 67 finished with value: -0.0974440724172911 and parameters: {'number_of_factors': 200, 'alpha_weight': 0.7154324415333144, 'regularization': 0.14879458716943877}. Best is trial 63 with value: -0.10012063435717589.

Fold : 5
         Average NDCG : -0.0974440724172911

100%|██████████| 15/15 [00:01<00:00, 12.08it/s]
100%|██████████| 10/10 [00:00<00:00, 2786.17it/s]
100%|██████████| 15/15 [00:01<00:00, 12.11it/s]
100%|██████████| 10/10 [00:00<00:00, 3166.71it/s]
100%|██████████| 15/15 [00:01<00:00, 11.94it/s]
100%|██████████| 10/10 [00:00<00:00, 2960.20it/s]
100%|██████████| 15/15 [00:01<00:00, 12.22it/s]
100%|██████████| 11/11 [00:00<00:00, 2956.38it/s]
100%|██████████| 15/15 [00:01<00:00, 11.56it/s]
100%|██████████| 10/10 [00:00<00:00, 3158.60it/s]
[I 2023-07-08 22:23:28,720] Trial 68 finished with value: -0.08930364380264405 and parameters: {'number_of_factors': 200, 'alpha_weight': 0.4086150416717321, 'regularization': 0.12376417003393872}. Best is trial 63 with value: -0.10012063435717589.

Fold : 5
         Average NDCG : -0.08930364380264405

100%|██████████| 15/15 [00:01<00:00, 11.68it/s]
100%|██████████| 10/10 [00:00<00:00, 2961.87it/s]
100%|██████████| 15/15 [00:01<00:00, 12.09it/s]
100%|██████████| 10/10 [00:00<00:00, 3038.25it/s]
100%|██████████| 15/15 [00:01<00:00, 11.34it/s]
100%|██████████| 10/10 [00:00<00:00, 2823.50it/s]
100%|██████████| 15/15 [00:01<00:00, 11.29it/s]
100%|██████████| 11/11 [00:00<00:00, 3173.13it/s]
100%|██████████| 15/15 [00:01<00:00, 11.34it/s]
100%|██████████| 10/10 [00:00<00:00, 2379.88it/s]
[I 2023-07-08 22:23:35,491] Trial 69 finished with value: -0.09124064554436034 and parameters: {'number_of_factors': 200, 'alpha_weight': 0.694046786797371, 'regularization': 0.1504245587374656}. Best is trial 63 with value: -0.10012063435717589.

Fold : 5
         Average NDCG : -0.09124064554436034

100%|██████████| 15/15 [00:01<00:00, 13.40it/s]
100%|██████████| 10/10 [00:00<00:00, 4225.15it/s]
100%|██████████| 15/15 [00:01<00:00, 12.99it/s]
100%|██████████| 10/10 [00:00<00:00, 3738.24it/s]
100%|██████████| 15/15 [00:01<00:00, 11.27it/s]
100%|██████████| 10/10 [00:00<00:00, 4175.51it/s]
100%|██████████| 15/15 [00:01<00:00, 11.50it/s]
100%|██████████| 11/11 [00:00<00:00, 4049.27it/s]
100%|██████████| 15/15 [00:01<00:00, 13.11it/s]
100%|██████████| 10/10 [00:00<00:00, 4520.21it/s]
[I 2023-07-08 22:23:41,719] Trial 70 finished with value: -0.09975173311761157 and parameters: {'number_of_factors': 100, 'alpha_weight': 0.7978972576962944, 'regularization': 0.17633276258586753}. Best is trial 63 with value: -0.10012063435717589.

Fold : 5
         Average NDCG : -0.09975173311761157

100%|██████████| 15/15 [00:01<00:00, 13.66it/s]
100%|██████████| 10/10 [00:00<00:00, 4195.98it/s]
100%|██████████| 15/15 [00:01<00:00, 13.78it/s]
100%|██████████| 10/10 [00:00<00:00, 4041.14it/s]
100%|██████████| 15/15 [00:01<00:00, 13.28it/s]
100%|██████████| 10/10 [00:00<00:00, 4383.22it/s]
100%|██████████| 15/15 [00:01<00:00, 13.67it/s]
100%|██████████| 11/11 [00:00<00:00, 4247.20it/s]
100%|██████████| 15/15 [00:01<00:00, 13.53it/s]
100%|██████████| 10/10 [00:00<00:00, 4512.43it/s]
[I 2023-07-08 22:23:47,416] Trial 71 finished with value: -0.09837415396083268 and parameters: {'number_of_factors': 100, 'alpha_weight': 0.7735565396710037, 'regularization': 0.1763049846316826}. Best is trial 63 with value: -0.10012063435717589.

Fold : 5
         Average NDCG : -0.09837415396083268

100%|██████████| 15/15 [00:01<00:00, 13.44it/s]
100%|██████████| 10/10 [00:00<00:00, 3853.29it/s]
100%|██████████| 15/15 [00:01<00:00, 13.47it/s]
100%|██████████| 10/10 [00:00<00:00, 4192.63it/s]
100%|██████████| 15/15 [00:01<00:00, 13.32it/s]
100%|██████████| 10/10 [00:00<00:00, 4572.45it/s]
100%|██████████| 15/15 [00:01<00:00, 12.97it/s]
100%|██████████| 11/11 [00:00<00:00, 4421.40it/s]
100%|██████████| 15/15 [00:01<00:00, 12.95it/s]
100%|██████████| 10/10 [00:00<00:00, 3482.77it/s]
[I 2023-07-08 22:23:53,253] Trial 72 finished with value: -0.09692932342899901 and parameters: {'number_of_factors': 100, 'alpha_weight': 0.7808127710655757, 'regularization': 0.1766935144306719}. Best is trial 63 with value: -0.10012063435717589.

Fold : 5
         Average NDCG : -0.09692932342899901

100%|██████████| 15/15 [00:01<00:00, 13.68it/s]
100%|██████████| 10/10 [00:00<00:00, 4112.06it/s]
100%|██████████| 15/15 [00:01<00:00, 13.52it/s]
100%|██████████| 10/10 [00:00<00:00, 3049.96it/s]
100%|██████████| 15/15 [00:01<00:00, 13.59it/s]
100%|██████████| 10/10 [00:00<00:00, 4087.62it/s]
100%|██████████| 15/15 [00:01<00:00, 13.73it/s]
100%|██████████| 11/11 [00:00<00:00, 4057.10it/s]
100%|██████████| 15/15 [00:01<00:00, 12.74it/s]
100%|██████████| 10/10 [00:00<00:00, 4218.77it/s]
[I 2023-07-08 22:23:58,991] Trial 73 finished with value: -0.09594929071928224 and parameters: {'number_of_factors': 100, 'alpha_weight': 0.7078051312064723, 'regularization': 0.15966435205812107}. Best is trial 63 with value: -0.10012063435717589.

Fold : 5
         Average NDCG : -0.09594929071928224

100%|██████████| 15/15 [00:01<00:00, 13.53it/s]
100%|██████████| 10/10 [00:00<00:00, 4280.34it/s]
100%|██████████| 15/15 [00:01<00:00, 13.74it/s]
100%|██████████| 10/10 [00:00<00:00, 3862.16it/s]
100%|██████████| 15/15 [00:01<00:00, 13.48it/s]
100%|██████████| 10/10 [00:00<00:00, 2695.57it/s]
100%|██████████| 15/15 [00:01<00:00, 13.69it/s]
100%|██████████| 11/11 [00:00<00:00, 4239.40it/s]
100%|██████████| 15/15 [00:01<00:00, 13.62it/s]
100%|██████████| 10/10 [00:00<00:00, 4176.76it/s]
[I 2023-07-08 22:24:04,679] Trial 74 finished with value: -0.09221985840502128 and parameters: {'number_of_factors': 100, 'alpha_weight': 0.8473250282425392, 'regularization': 0.17545236924054483}. Best is trial 63 with value: -0.10012063435717589.

Fold : 5
         Average NDCG : -0.09221985840502128

100%|██████████| 15/15 [00:01<00:00, 13.56it/s]
100%|██████████| 10/10 [00:00<00:00, 3908.59it/s]
100%|██████████| 15/15 [00:01<00:00, 13.75it/s]
100%|██████████| 10/10 [00:00<00:00, 4034.54it/s]
100%|██████████| 15/15 [00:01<00:00, 13.54it/s]
100%|██████████| 10/10 [00:00<00:00, 4274.23it/s]
100%|██████████| 15/15 [00:01<00:00, 13.63it/s]
100%|██████████| 11/11 [00:00<00:00, 2900.99it/s]
100%|██████████| 15/15 [00:01<00:00, 13.56it/s]
100%|██████████| 10/10 [00:00<00:00, 3981.30it/s]
[I 2023-07-08 22:24:10,359] Trial 75 finished with value: -0.09596068201814414 and parameters: {'number_of_factors': 100, 'alpha_weight': 0.5595529578519609, 'regularization': 0.14699959126621936}. Best is trial 63 with value: -0.10012063435717589.

Fold : 5
         Average NDCG : -0.09596068201814414

100%|██████████| 15/15 [00:01<00:00, 13.53it/s]
100%|██████████| 10/10 [00:00<00:00, 3086.54it/s]
100%|██████████| 15/15 [00:01<00:00, 13.63it/s]
100%|██████████| 10/10 [00:00<00:00, 3413.89it/s]
100%|██████████| 15/15 [00:01<00:00, 13.58it/s]
100%|██████████| 10/10 [00:00<00:00, 4571.45it/s]
100%|██████████| 15/15 [00:01<00:00, 13.86it/s]
100%|██████████| 11/11 [00:00<00:00, 3980.79it/s]
100%|██████████| 15/15 [00:01<00:00, 13.45it/s]
100%|██████████| 10/10 [00:00<00:00, 4301.85it/s]
[I 2023-07-08 22:24:16,047] Trial 76 finished with value: -0.09680103467182086 and parameters: {'number_of_factors': 100, 'alpha_weight': 0.6205350500198128, 'regularization': 0.18052008595613145}. Best is trial 63 with value: -0.10012063435717589.

Fold : 5
         Average NDCG : -0.09680103467182086

100%|██████████| 15/15 [00:01<00:00, 13.55it/s]
100%|██████████| 10/10 [00:00<00:00, 4289.97it/s]
100%|██████████| 15/15 [00:01<00:00, 12.88it/s]
100%|██████████| 10/10 [00:00<00:00, 4182.59it/s]
100%|██████████| 15/15 [00:01<00:00, 13.43it/s]
100%|██████████| 10/10 [00:00<00:00, 4009.47it/s]
100%|██████████| 15/15 [00:01<00:00, 13.87it/s]
100%|██████████| 11/11 [00:00<00:00, 4312.30it/s]
100%|██████████| 15/15 [00:01<00:00, 13.75it/s]
100%|██████████| 10/10 [00:00<00:00, 3285.27it/s]
[I 2023-07-08 22:24:21,785] Trial 77 finished with value: -0.09690939423060946 and parameters: {'number_of_factors': 100, 'alpha_weight': 0.7745345154907437, 'regularization': 0.16063621563693467}. Best is trial 63 with value: -0.10012063435717589.

Fold : 5
         Average NDCG : -0.09690939423060946

100%|██████████| 15/15 [00:01<00:00, 13.21it/s]
100%|██████████| 10/10 [00:00<00:00, 4685.33it/s]
100%|██████████| 15/15 [00:01<00:00, 13.74it/s]
100%|██████████| 10/10 [00:00<00:00, 4382.76it/s]
100%|██████████| 15/15 [00:01<00:00, 13.69it/s]
100%|██████████| 10/10 [00:00<00:00, 4174.27it/s]
100%|██████████| 15/15 [00:01<00:00, 13.08it/s]
100%|██████████| 11/11 [00:00<00:00, 4388.18it/s]
100%|██████████| 15/15 [00:01<00:00, 13.55it/s]
100%|██████████| 10/10 [00:00<00:00, 4597.51it/s]
[I 2023-07-08 22:24:27,529] Trial 78 finished with value: -0.09540472832170041 and parameters: {'number_of_factors': 100, 'alpha_weight': 0.8886849436825542, 'regularization': 0.13293483668012143}. Best is trial 63 with value: -0.10012063435717589.

Fold : 5
         Average NDCG : -0.09540472832170041

100%|██████████| 15/15 [00:01<00:00, 13.65it/s]
100%|██████████| 10/10 [00:00<00:00, 4223.02it/s]
100%|██████████| 15/15 [00:01<00:00, 13.49it/s]
100%|██████████| 10/10 [00:00<00:00, 4274.23it/s]
100%|██████████| 15/15 [00:01<00:00, 13.71it/s]
100%|██████████| 10/10 [00:00<00:00, 4254.29it/s]
100%|██████████| 15/15 [00:01<00:00, 13.81it/s]
100%|██████████| 11/11 [00:00<00:00, 4394.87it/s]
100%|██████████| 15/15 [00:01<00:00, 13.39it/s]
100%|██████████| 10/10 [00:00<00:00, 4217.50it/s]
[I 2023-07-08 22:24:33,211] Trial 79 finished with value: -0.0926250084792915 and parameters: {'number_of_factors': 100, 'alpha_weight': 0.4950817553150689, 'regularization': 0.16732289120559193}. Best is trial 63 with value: -0.10012063435717589.

Fold : 5
         Average NDCG : -0.0926250084792915

100%|██████████| 15/15 [00:01<00:00, 13.66it/s]
100%|██████████| 10/10 [00:00<00:00, 4441.24it/s]
100%|██████████| 15/15 [00:01<00:00, 13.78it/s]
100%|██████████| 10/10 [00:00<00:00, 3953.53it/s]
100%|██████████| 15/15 [00:01<00:00, 13.46it/s]
100%|██████████| 10/10 [00:00<00:00, 4322.69it/s]
100%|██████████| 15/15 [00:01<00:00, 13.75it/s]
100%|██████████| 11/11 [00:00<00:00, 4873.49it/s]
100%|██████████| 15/15 [00:01<00:00, 13.68it/s]
100%|██████████| 10/10 [00:00<00:00, 4267.27it/s]
[I 2023-07-08 22:24:38,874] Trial 80 finished with value: -0.09691848176911656 and parameters: {'number_of_factors': 100, 'alpha_weight': 0.6949372466700566, 'regularization': 0.14967027321036597}. Best is trial 63 with value: -0.10012063435717589.

Fold : 5
         Average NDCG : -0.09691848176911656

100%|██████████| 15/15 [00:01<00:00, 12.11it/s]
100%|██████████| 10/10 [00:00<00:00, 2980.60it/s]
100%|██████████| 15/15 [00:01<00:00, 11.72it/s]
100%|██████████| 10/10 [00:00<00:00, 3023.79it/s]
100%|██████████| 15/15 [00:01<00:00, 11.44it/s]
100%|██████████| 10/10 [00:00<00:00, 3165.99it/s]
100%|██████████| 15/15 [00:01<00:00, 12.35it/s]
100%|██████████| 11/11 [00:00<00:00, 3149.31it/s]
100%|██████████| 15/15 [00:01<00:00, 12.16it/s]
100%|██████████| 10/10 [00:00<00:00, 2990.38it/s]
[I 2023-07-08 22:24:45,422] Trial 81 finished with value: -0.08856091704314337 and parameters: {'number_of_factors': 200, 'alpha_weight': 0.43352525481663573, 'regularization': 0.11816733838896884}. Best is trial 63 with value: -0.10012063435717589.

Fold : 5
         Average NDCG : -0.08856091704314337

100%|██████████| 15/15 [00:01<00:00, 12.19it/s]
100%|██████████| 10/10 [00:00<00:00, 3040.89it/s]
100%|██████████| 15/15 [00:01<00:00, 12.20it/s]
100%|██████████| 10/10 [00:00<00:00, 3081.78it/s]
100%|██████████| 15/15 [00:01<00:00, 11.31it/s]
100%|██████████| 10/10 [00:00<00:00, 2661.36it/s]
100%|██████████| 15/15 [00:01<00:00, 10.91it/s]
100%|██████████| 11/11 [00:00<00:00, 3029.17it/s]
100%|██████████| 15/15 [00:01<00:00, 12.13it/s]
100%|██████████| 10/10 [00:00<00:00, 3017.70it/s]
[I 2023-07-08 22:24:52,104] Trial 82 finished with value: -0.09596770643679679 and parameters: {'number_of_factors': 200, 'alpha_weight': 0.5975061513643953, 'regularization': 0.18402734447344682}. Best is trial 63 with value: -0.10012063435717589.

Fold : 5
         Average NDCG : -0.09596770643679679

100%|██████████| 15/15 [00:01<00:00,  9.10it/s]
100%|██████████| 10/10 [00:00<00:00, 2531.26it/s]
100%|██████████| 15/15 [00:01<00:00,  9.43it/s]
100%|██████████| 10/10 [00:00<00:00, 1968.60it/s]
100%|██████████| 15/15 [00:02<00:00,  7.45it/s]
100%|██████████| 10/10 [00:00<00:00, 684.35it/s]
100%|██████████| 15/15 [00:02<00:00,  6.66it/s]
100%|██████████| 11/11 [00:00<00:00, 2814.11it/s]
100%|██████████| 15/15 [00:02<00:00,  7.39it/s]
100%|██████████| 10/10 [00:00<00:00, 2935.54it/s]
[I 2023-07-08 22:25:01,956] Trial 83 finished with value: -0.09263244741434515 and parameters: {'number_of_factors': 200, 'alpha_weight': 0.5226628684265533, 'regularization': 0.13093754241861996}. Best is trial 63 with value: -0.10012063435717589.

Fold : 5
         Average NDCG : -0.09263244741434515

100%|██████████| 15/15 [00:01<00:00, 10.58it/s]
100%|██████████| 10/10 [00:00<00:00, 2866.72it/s]
100%|██████████| 15/15 [00:01<00:00,  7.55it/s]
100%|██████████| 10/10 [00:00<00:00, 2524.71it/s]
100%|██████████| 15/15 [00:01<00:00,  8.07it/s]
100%|██████████| 10/10 [00:00<00:00, 2657.48it/s]
100%|██████████| 15/15 [00:01<00:00, 10.00it/s]
100%|██████████| 11/11 [00:00<00:00, 2866.03it/s]
100%|██████████| 15/15 [00:01<00:00, 11.29it/s]
100%|██████████| 10/10 [00:00<00:00, 2875.96it/s]
[I 2023-07-08 22:25:10,358] Trial 84 finished with value: -0.09382895272099816 and parameters: {'number_of_factors': 200, 'alpha_weight': 0.7764225927589634, 'regularization': 0.1104578424805572}. Best is trial 63 with value: -0.10012063435717589.

Fold : 5
         Average NDCG : -0.09382895272099816

100%|██████████| 15/15 [00:01<00:00, 11.76it/s]
100%|██████████| 10/10 [00:00<00:00, 4074.51it/s]
100%|██████████| 15/15 [00:01<00:00, 12.70it/s]
100%|██████████| 10/10 [00:00<00:00, 3560.23it/s]
100%|██████████| 15/15 [00:01<00:00, 11.52it/s]
100%|██████████| 10/10 [00:00<00:00, 3858.96it/s]
100%|██████████| 15/15 [00:01<00:00, 11.21it/s]
100%|██████████| 11/11 [00:00<00:00, 3639.45it/s]
100%|██████████| 15/15 [00:01<00:00, 12.92it/s]
100%|██████████| 10/10 [00:00<00:00, 3781.72it/s]
[I 2023-07-08 22:25:16,792] Trial 85 finished with value: -0.09522077580307041 and parameters: {'number_of_factors': 100, 'alpha_weight': 0.45415809640517163, 'regularization': 0.1624813201874144}. Best is trial 63 with value: -0.10012063435717589.

Fold : 5
         Average NDCG : -0.09522077580307041

100%|██████████| 15/15 [00:01<00:00, 10.47it/s]
100%|██████████| 10/10 [00:00<00:00, 2231.84it/s]
100%|██████████| 15/15 [00:01<00:00, 10.48it/s]
100%|██████████| 10/10 [00:00<00:00, 2490.83it/s]
100%|██████████| 15/15 [00:01<00:00, 10.48it/s]
100%|██████████| 10/10 [00:00<00:00, 2006.94it/s]
100%|██████████| 15/15 [00:01<00:00, 11.16it/s]
100%|██████████| 11/11 [00:00<00:00, 2506.37it/s]
100%|██████████| 15/15 [00:01<00:00,  9.68it/s]
100%|██████████| 10/10 [00:00<00:00, 2330.82it/s]
[I 2023-07-08 22:25:24,628] Trial 86 finished with value: -0.09663976343159221 and parameters: {'number_of_factors': 300, 'alpha_weight': 0.3728801247268475, 'regularization': 0.14540701474032042}. Best is trial 63 with value: -0.10012063435717589.

Fold : 5
         Average NDCG : -0.09663976343159221

100%|██████████| 15/15 [00:01<00:00,  9.41it/s]
100%|██████████| 10/10 [00:00<00:00, 3010.55it/s]
100%|██████████| 15/15 [00:01<00:00, 11.56it/s]
100%|██████████| 10/10 [00:00<00:00, 1710.56it/s]
100%|██████████| 15/15 [00:02<00:00,  7.33it/s]
100%|██████████| 10/10 [00:00<00:00, 2548.64it/s]
100%|██████████| 15/15 [00:01<00:00, 10.85it/s]
100%|██████████| 11/11 [00:00<00:00, 2874.78it/s]
100%|██████████| 15/15 [00:01<00:00, 10.17it/s]
100%|██████████| 10/10 [00:00<00:00, 2870.65it/s]
[I 2023-07-08 22:25:32,737] Trial 87 finished with value: -0.098445725915853 and parameters: {'number_of_factors': 200, 'alpha_weight': 0.6357702607386033, 'regularization': 0.18445242517620386}. Best is trial 63 with value: -0.10012063435717589.

Fold : 5
         Average NDCG : -0.098445725915853

100%|██████████| 15/15 [00:01<00:00, 10.59it/s]
100%|██████████| 10/10 [00:00<00:00, 2400.31it/s]
100%|██████████| 15/15 [00:01<00:00,  9.72it/s]
100%|██████████| 10/10 [00:00<00:00, 2897.22it/s]
100%|██████████| 15/15 [00:01<00:00, 10.00it/s]
100%|██████████| 10/10 [00:00<00:00, 2757.42it/s]
100%|██████████| 15/15 [00:01<00:00, 11.05it/s]
100%|██████████| 11/11 [00:00<00:00, 2963.79it/s]
100%|██████████| 15/15 [00:01<00:00, 11.28it/s]
100%|██████████| 10/10 [00:00<00:00, 2973.42it/s]
[I 2023-07-08 22:25:40,167] Trial 88 finished with value: -0.0980587441057623 and parameters: {'number_of_factors': 200, 'alpha_weight': 0.5820867556490855, 'regularization': 0.19035823445308117}. Best is trial 63 with value: -0.10012063435717589.

Fold : 5
         Average NDCG : -0.0980587441057623

100%|██████████| 15/15 [00:02<00:00,  7.01it/s]
100%|██████████| 10/10 [00:00<00:00, 1290.59it/s]
100%|██████████| 15/15 [00:02<00:00,  6.93it/s]
100%|██████████| 10/10 [00:00<00:00, 507.53it/s]
100%|██████████| 15/15 [00:02<00:00,  6.16it/s]
100%|██████████| 10/10 [00:00<00:00, 1817.05it/s]
100%|██████████| 15/15 [00:02<00:00,  6.97it/s]
100%|██████████| 11/11 [00:00<00:00, 1522.58it/s]
100%|██████████| 15/15 [00:02<00:00,  7.25it/s]
100%|██████████| 10/10 [00:00<00:00, 1943.97it/s]
[I 2023-07-08 22:25:51,889] Trial 89 finished with value: -0.09144438486654884 and parameters: {'number_of_factors': 400, 'alpha_weight': 0.5216792013795646, 'regularization': 0.1998080348102378}. Best is trial 63 with value: -0.10012063435717589.

Fold : 5
         Average NDCG : -0.09144438486654884

100%|██████████| 15/15 [00:01<00:00, 10.98it/s]
100%|██████████| 10/10 [00:00<00:00, 2834.18it/s]
100%|██████████| 15/15 [00:01<00:00, 11.72it/s]
100%|██████████| 10/10 [00:00<00:00, 2939.86it/s]
100%|██████████| 15/15 [00:01<00:00, 11.76it/s]
100%|██████████| 10/10 [00:00<00:00, 2829.78it/s]
100%|██████████| 15/15 [00:01<00:00, 10.99it/s]
100%|██████████| 11/11 [00:00<00:00, 3139.45it/s]
100%|██████████| 15/15 [00:01<00:00, 11.65it/s]
100%|██████████| 10/10 [00:00<00:00, 2928.78it/s]
[I 2023-07-08 22:25:58,746] Trial 90 finished with value: -0.089634401377467 and parameters: {'number_of_factors': 200, 'alpha_weight': 0.6456260953338119, 'regularization': 0.174455327095658}. Best is trial 63 with value: -0.10012063435717589.

Fold : 5
         Average NDCG : -0.089634401377467

100%|██████████| 15/15 [00:01<00:00,  8.78it/s]
100%|██████████| 10/10 [00:00<00:00, 2668.13it/s]
100%|██████████| 15/15 [00:01<00:00, 10.25it/s]
100%|██████████| 10/10 [00:00<00:00, 2375.57it/s]
100%|██████████| 15/15 [00:01<00:00, 11.02it/s]
100%|██████████| 10/10 [00:00<00:00, 2812.14it/s]
100%|██████████| 15/15 [00:01<00:00, 10.19it/s]
100%|██████████| 11/11 [00:00<00:00, 2750.36it/s]
100%|██████████| 15/15 [00:01<00:00,  9.35it/s]
100%|██████████| 10/10 [00:00<00:00, 2579.68it/s]
[I 2023-07-08 22:26:06,637] Trial 91 finished with value: -0.09518157252811212 and parameters: {'number_of_factors': 200, 'alpha_weight': 0.7392375299741141, 'regularization': 0.18646806453659318}. Best is trial 63 with value: -0.10012063435717589.

Fold : 5
         Average NDCG : -0.09518157252811212

100%|██████████| 15/15 [00:01<00:00,  9.95it/s]
100%|██████████| 10/10 [00:00<00:00, 2719.69it/s]
100%|██████████| 15/15 [00:01<00:00, 11.28it/s]
100%|██████████| 10/10 [00:00<00:00, 2807.81it/s]
100%|██████████| 15/15 [00:01<00:00, 11.46it/s]
100%|██████████| 10/10 [00:00<00:00, 2780.45it/s]
100%|██████████| 15/15 [00:01<00:00, 11.39it/s]
100%|██████████| 11/11 [00:00<00:00, 2967.80it/s]
100%|██████████| 15/15 [00:01<00:00, 11.46it/s]
100%|██████████| 10/10 [00:00<00:00, 2768.15it/s]
[I 2023-07-08 22:26:13,711] Trial 92 finished with value: -0.09196785056669082 and parameters: {'number_of_factors': 200, 'alpha_weight': 0.583772472571013, 'regularization': 0.16010716609975353}. Best is trial 63 with value: -0.10012063435717589.

Fold : 5
         Average NDCG : -0.09196785056669082

100%|██████████| 15/15 [00:01<00:00, 11.03it/s]
100%|██████████| 10/10 [00:00<00:00, 2467.67it/s]
100%|██████████| 15/15 [00:01<00:00, 11.53it/s]
100%|██████████| 10/10 [00:00<00:00, 3002.15it/s]
100%|██████████| 15/15 [00:01<00:00, 10.88it/s]
100%|██████████| 10/10 [00:00<00:00, 2622.92it/s]
100%|██████████| 15/15 [00:01<00:00, 10.24it/s]
100%|██████████| 11/11 [00:00<00:00, 2983.34it/s]
100%|██████████| 15/15 [00:01<00:00,  9.61it/s]
100%|██████████| 10/10 [00:00<00:00, 2823.50it/s]
[I 2023-07-08 22:26:21,071] Trial 93 finished with value: -0.096394819259735 and parameters: {'number_of_factors': 200, 'alpha_weight': 0.8962066553881486, 'regularization': 0.18654897810427198}. Best is trial 63 with value: -0.10012063435717589.

Fold : 5
         Average NDCG : -0.096394819259735

100%|██████████| 15/15 [00:01<00:00, 11.72it/s]
100%|██████████| 10/10 [00:00<00:00, 2325.78it/s]
100%|██████████| 15/15 [00:01<00:00, 11.37it/s]
100%|██████████| 10/10 [00:00<00:00, 2797.88it/s]
100%|██████████| 15/15 [00:01<00:00, 11.00it/s]
100%|██████████| 10/10 [00:00<00:00, 2671.53it/s]
100%|██████████| 15/15 [00:01<00:00, 11.80it/s]
100%|██████████| 11/11 [00:00<00:00, 2734.71it/s]
100%|██████████| 15/15 [00:01<00:00, 11.69it/s]
100%|██████████| 10/10 [00:00<00:00, 2925.92it/s]
[I 2023-07-08 22:26:27,867] Trial 94 finished with value: -0.09619013405748769 and parameters: {'number_of_factors': 200, 'alpha_weight': 0.6766515484923274, 'regularization': 0.17414452591485446}. Best is trial 63 with value: -0.10012063435717589.

Fold : 5
         Average NDCG : -0.09619013405748769

100%|██████████| 15/15 [00:01<00:00, 11.82it/s]
100%|██████████| 10/10 [00:00<00:00, 3065.12it/s]
100%|██████████| 15/15 [00:01<00:00, 12.22it/s]
100%|██████████| 10/10 [00:00<00:00, 2787.28it/s]
100%|██████████| 15/15 [00:01<00:00, 11.88it/s]
100%|██████████| 10/10 [00:00<00:00, 2765.05it/s]
100%|██████████| 15/15 [00:01<00:00, 11.45it/s]
100%|██████████| 11/11 [00:00<00:00, 2892.99it/s]
100%|██████████| 15/15 [00:01<00:00, 11.99it/s]
100%|██████████| 10/10 [00:00<00:00, 2580.63it/s]
[I 2023-07-08 22:26:34,451] Trial 95 finished with value: -0.09533786500912693 and parameters: {'number_of_factors': 200, 'alpha_weight': 0.8135862373664264, 'regularization': 0.14083904543960862}. Best is trial 63 with value: -0.10012063435717589.

Fold : 5
         Average NDCG : -0.09533786500912693

100%|██████████| 15/15 [00:01<00:00, 13.12it/s]
100%|██████████| 10/10 [00:00<00:00, 4539.78it/s]
100%|██████████| 15/15 [00:01<00:00, 13.58it/s]
100%|██████████| 10/10 [00:00<00:00, 3611.42it/s]
100%|██████████| 15/15 [00:01<00:00, 13.20it/s]
100%|██████████| 10/10 [00:00<00:00, 4189.28it/s]
100%|██████████| 15/15 [00:01<00:00, 12.83it/s]
100%|██████████| 11/11 [00:00<00:00, 3961.31it/s]
100%|██████████| 15/15 [00:01<00:00, 13.16it/s]
100%|██████████| 10/10 [00:00<00:00, 4214.11it/s]
[I 2023-07-08 22:26:40,317] Trial 96 finished with value: -0.10010153835510718 and parameters: {'number_of_factors': 100, 'alpha_weight': 0.5792858572625689, 'regularization': 0.15524079393608714}. Best is trial 63 with value: -0.10012063435717589.

Fold : 5
         Average NDCG : -0.10010153835510718

100%|██████████| 15/15 [00:01<00:00, 13.30it/s]
100%|██████████| 10/10 [00:00<00:00, 4029.11it/s]
100%|██████████| 15/15 [00:01<00:00, 12.97it/s]
100%|██████████| 10/10 [00:00<00:00, 4478.22it/s]
100%|██████████| 15/15 [00:01<00:00, 13.39it/s]
100%|██████████| 10/10 [00:00<00:00, 4495.02it/s]
100%|██████████| 15/15 [00:01<00:00, 13.54it/s]
100%|██████████| 11/11 [00:00<00:00, 4559.93it/s]
100%|██████████| 15/15 [00:01<00:00, 13.30it/s]
100%|██████████| 10/10 [00:00<00:00, 4165.15it/s]
[I 2023-07-08 22:26:46,133] Trial 97 finished with value: -0.09322841993439689 and parameters: {'number_of_factors': 100, 'alpha_weight': 0.5851007617770291, 'regularization': 0.18806454781814408}. Best is trial 63 with value: -0.10012063435717589.

Fold : 5
         Average NDCG : -0.09322841993439689

100%|██████████| 15/15 [00:01<00:00, 13.40it/s]
100%|██████████| 10/10 [00:00<00:00, 3291.72it/s]
100%|██████████| 15/15 [00:01<00:00, 13.38it/s]
100%|██████████| 10/10 [00:00<00:00, 3833.22it/s]
100%|██████████| 15/15 [00:01<00:00, 13.37it/s]
100%|██████████| 10/10 [00:00<00:00, 2798.07it/s]
100%|██████████| 15/15 [00:01<00:00, 13.69it/s]
100%|██████████| 11/11 [00:00<00:00, 4667.88it/s]
100%|██████████| 15/15 [00:01<00:00, 13.47it/s]
100%|██████████| 10/10 [00:00<00:00, 3977.91it/s]
[I 2023-07-08 22:26:51,891] Trial 98 finished with value: -0.09928596218169074 and parameters: {'number_of_factors': 100, 'alpha_weight': 0.5138249717326794, 'regularization': 0.16681086504667295}. Best is trial 63 with value: -0.10012063435717589.

Fold : 5
         Average NDCG : -0.09928596218169074

100%|██████████| 15/15 [00:01<00:00, 12.58it/s]
100%|██████████| 10/10 [00:00<00:00, 3879.30it/s]
100%|██████████| 15/15 [00:01<00:00, 13.58it/s]
100%|██████████| 10/10 [00:00<00:00, 3368.11it/s]
100%|██████████| 15/15 [00:01<00:00, 13.59it/s]
100%|██████████| 10/10 [00:00<00:00, 3978.28it/s]
100%|██████████| 15/15 [00:01<00:00, 13.11it/s]
100%|██████████| 11/11 [00:00<00:00, 3033.56it/s]
100%|██████████| 15/15 [00:01<00:00, 11.66it/s]
100%|██████████| 10/10 [00:00<00:00, 3605.83it/s]
[I 2023-07-08 22:26:57,902] Trial 99 finished with value: -0.09925072214045776 and parameters: {'number_of_factors': 100, 'alpha_weight': 0.5097051938957499, 'regularization': 0.16799704422342204}. Best is trial 63 with value: -0.10012063435717589.

Fold : 5
         Average NDCG : -0.09925072214045776

### Measure Tuned Model on Test Set

In [61]:
model_als_tuned= AlternatingLeastSquares(factors=100,
                                    regularization=0.16799704422342204,
                                    alpha=0.5097051938957499)
model_als_tuned.fit(train_data)

100%|██████████| 15/15 [00:06<00:00,  2.17it/s]

In [62]:
final_tuned_metrics = ranking_metrics_at_k(model=model_als_tuned,
                                   train_user_items=train_data,
                                   test_user_items=test_data)

100%|██████████| 1878/1878 [00:00<00:00, 5369.62it/s]

In [63]:
final_tuned_metrics

{'precision': 0.16635468872652617,
 'map': 0.0844339689737369,
 'ndcg': 0.17261162377361844,
 'auc': 0.574831593418623}

### Fit Model on All Training Data

In [44]:
final_als= AlternatingLeastSquares(factors=100,
                                    regularization=0.16799704422342204,
                                    alpha=0.5097051938957499)
final_als.fit(implicit_utility)

  0%|          | 0/15 [00:00<?, ?it/s]100%|██████████| 15/15 [00:09<00:00,  1.52it/s]

In [65]:

def load_artist_data() : 
    artist_path = "interim_artists.csv"
    artist_data = pd.read_csv(artist_path,usecols=['id','name'])
    return artist_data

In [70]:
id_rec = final_als.recommend(userid=2,
                    user_items=train_data[2])
artists_ordered_ids = id_rec[0]

artists_id = [ordered_id_to_artist_id[id] for id in artists_ordered_ids ]
artist_data = load_artist_data()

artist_name = artist_data.loc[artist_data['id'].isin(artists_id),'name'].tolist()
artist_name

['Pleq',
 'Max Richter',
 'Celer',
 'Pjusk',
 'Pleq & Segue',
 'Go Koyashiki',
 "Dustin O'Halloran",
 'Fjordne',
 'Deru',
 'Library Tapes']

In [ ]:
##

### Save Model

In [66]:
import joblib 
joblib.dump(final_als,"../models/als_tuned_model.pkl")

['../models/als_tuned_model.pkl']

#### Sanity Check on Recommendation